apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.datadog.apiSecret.secretName }}
stringData:
  api-key: {{ (index .Values "datadog-operator").apiKey }}
  app-key: {{ (index .Values "datadog-operator").appKey }}

