coroot:
  corootCE:
    ingress:
      enabled: true
      className: networking-traefik
      hostname: metrics.i.unerror.network
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.entrypoints: websecure-tsnet
        traefik.ingress.kubernetes.io/router.tls: "true"
        traefik.ingress.kubernetes.io/router.tls.options: default
      hosts:
        - host: metrics.i.unerror.network
          paths:
            - path: /
              pathType: ImplementationSpecific
              port: 3301
      tls:
        - hosts:
            - metrics.i.unerror.network
          secretName: metrics-internal-ingress-tls
  clickhouse:
    persistence:
      size: 25Gi
  corootClusterAgent:
    config:
      coroot_url: http://monitoring-coroot:8080
  node-agent:
    tracesEndpoint: http://monitoring-coroot:8080/v1/traces
    logsEndpoint: http://monitoring-coroot:8080/v1/logs
    profilesEndpoint: http://monitoring-coroot:8080/v1/profiles
