coroot:
  corootCE:
    ingress:
      enabled: true
      className: networking-traefik
      hostname: metrics.unerror.network
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.entrypoints: websecure-tsnet
        traefik.ingress.kubernetes.io/router.tls: "true"
        traefik.ingress.kubernetes.io/router.tls.options: default
      hosts:
        - host: metrics.unerror.network
          paths:
            - path: /
              pathType: ImplementationSpecific
              port: 3301
      tls:
        - hosts:
            - metrics.unerror.network
          secretName: metrics-ingress-tls

  clickhouse:
    persistence:
      size: 25Gi
