apiVersion: v1
kind: Secret
metadata:
  namespace: kube-system
  name: {{ include "csi-s3.fullname" . }}-s3
  namespace: kube-system
stringData:
  accessKeyID: {{ .Values.s3.accessKeyId }}
  secretAccessKey: {{ .Values.s3.secretAccessKey }}
  endpoint: {{ .Values.s3.endpoint }}
  region: {{ .Values.s3.region | default ""}}
