---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: s3-default
provisioner: ch.ctrox.csi.s3-driver
parameters:
  mounter: rclone
  csi.storage.k8s.io/provisioner-secret-name: {{ include "csi-s3.fullname" . }}-s3
  csi.storage.k8s.io/provisioner-secret-namespace: kube-system
  csi.storage.k8s.io/controller-publish-secret-name: {{ include "csi-s3.fullname" . }}-s3
  csi.storage.k8s.io/controller-publish-secret-namespace: kube-system
  csi.storage.k8s.io/node-stage-secret-name: {{ include "csi-s3.fullname" . }}-s3
  csi.storage.k8s.io/node-stage-secret-namespace: kube-system
  csi.storage.k8s.io/node-publish-secret-name: {{ include "csi-s3.fullname" . }}-s3
  csi.storage.k8s.io/node-publish-secret-namespace: kube-system