{{ $signkey := required "Generate a signing key (see README)" .Values.signing_key }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ma1sd.fullname" . }}
  labels:
{{ include "ma1sd.labels" . | indent 4 }}
data:
{{- if $signkey }}
  serial: {{ printf "{\"type\":\"Regular\",\"algo\":\"%s\",\"serial\":\"%s\"}" $signkey.algo $signkey.seriel | toJson | b64enc | quote }}
  signing.key: {{ $signkey.value | toJson | b64enc | quote }}
{{- end }}
  ma1sd.yaml: {{ .Values.config | toYaml | b64enc | quote }}
