{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "ma1sd.serviceAccountName" . }}
  labels:
{{ include "ma1sd.labels" . | indent 4 }}
{{- end -}}
