{{- if (index .Values "argo-cd").server.ingressRoute.enabled -}}
{{- $fullName := include "argocd.fullname" . -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}
spec:
	{{- with (index .Values "argo-cd").server.ingressRoute.entryPoints }}
  entryPoints:
    {{- toYaml . | nindent 4 }}
	{{- end }}

  {{- range (index .Values "argo-cd").server.ingressRoute.hosts }}
  routes:
    - match: Host(`{{ . }}`)
      kind: Rule
      services:
        - name: argocd-server
          port: 80
  {{- end }}
  tls:
    secretName: {{ (index .Values "argo-cd").server.ingressRoute.tls.secretName }}
{{- end }}