discourse:
  image:
    debug: true
  auth:
    email: community@unerror.network
    username: Unerror
  host: forums.unerror.network
  discourse:
    readinessProbe:
      enabled: false
    plugins:
    - https://github.com/discourse/discourse-chat-integration
    - https://github.com/discourse/discourse-openid-connect
    - https://github.com/codergautam/disable-email-verification-discourse
    - https://github.com/discourse/discourse-subscriptions
    - https://github.com/discourse/discourse-solved
    - https://github.com/discourse/discourse-follow
    - https://github.com/discourse/discourse-topic-voting
    - https://github.com/discourse/discourse-encrypt
    - https://github.com/discourse/discourse-yearly-review
  siteName: Unerror Community
  smtp:
    enabled: true
    host: smtp.sendgrid.net
    port: 587
    protocol: tls
  persistence:
    enabled: true
  postgresql:
    enabled: false
  externalDatabase:
    host: private-db-tor1-do-user-133480-0.b.db.ondigitalocean.com
    database: discourse
    port: 25061
    create: false
  ingress:
    enabled: true
    ingressClassName: networking-traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/router.tls.options: default
    hostname: forums.unerror.network
    tls: true
    extraHosts:
      - name: forum.unerror.network
        path: /
      - name: forums.unerror.com
        path: /
      - name: forum.unerror.com
        path: /
