discourse:
  auth:
    email: community@unerror.network
    username: Unerror
  host: forums.unerror.network
  siteName: Unerror Community
  smtp:
    enabled: true
    host: smtp.sendgrid.net
    port: 587
    protocol: tls
  persistence:
    enabled: true
    storageClass: s3-default
    accessModes:
      - ReadWriteMany
  postgresql:
    enabled: false
  externalDatabase:
    host: private-db-tor1-do-user-133480-0.b.db.ondigitalocean.com
    database: discourse
    port: 25060
    create: true
  ingress:
    enabled: true
    ingressClassName: networking-traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/router.tls.options: default
    hostname: forums.unerror.network
    tls: true
    extraHosts:
      - name: forum.unerror.network
        path: /
      - name: forums.unerror.com
        path: /
      - name: forum.unerror.com
        path: /
