cert-manager:
  ingressShim:
    defaultIssuerGroup: cert-manager.io
    defaultIssuerKind: ClusterIssuer
    defaultIssuerName: letsencrypt-prod
  installCRDs: true
external-dns:
  crd:
    create: true
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  cloudflare:
    proxied: true
  provider: cloudflare
  sources:
    - crd
    - ingress
    - service
