cert-manager:
  ingressShim:
    defaultIssuerGroup: cert-manager.io
    defaultIssuerKind: ClusterIssuer
    defaultIssuerName: letsencrypt-prod
  installCRDs: true
external-dns:
  extraArgs:
    annotation-filter: external-dns.alpha.kubernetes.io/exclude notin (true)
  crd:
    create: true
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  cloudflare:
    proxied: true
  provider: cloudflare
  sources:
    - crd
    - ingress
    - service
casdoorDataSourceName: ""
casdoor:
  image:
    tag: v1.446.1
  ingress:
    enabled: true
    className: networking-traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/router.tls.options: default
    hosts:
      - host: auth.unerror.network
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - hosts:
        - auth.unerror.network
        secretName: casdoor-ingress-tls
