cert-manager:
  ingressShim:
    defaultIssuerGroup: cert-manager.io
    defaultIssuerKind: ClusterIssuer
    defaultIssuerName: letsencrypt-prod
  installCRDs: true
external-dns:
  cloudflare:
    proxied: true
  provider: cloudflare
  sources:
    - ingress
    - service
ingress-nginx:
  controller:
    publishService:
      enabled: true
    ingressClassResource:
      default: true
    config:
      compute-full-forwarded-for: true
      use-forwarded-headers: true
      use-proxy-protocol: true
    kind: DaemonSet
    service:
      annotations:
        service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"
        external-dns.alpha.kubernetes.io/hostname: lb.unerror.network
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
  defaultBackend:
    enabled: true
  ingressClassResource:
    default: false
  tcp:
    6667: "default/chatbox-ircd:6667:PROXY:PROXY"
    6697: "default/chatbox-ircd:6697:PROXY:PROXY"
    3478: "une-sys/networking-coturn:3478:PROXY:PROXY"
  udp:
    3478: "une-sys/networking-coturn:3478:PROXY:PROXY"
