datadog-operator:
  apiKey: ""
datadog:
  logs:
    enabled: true
    containerCollectAll: true
  securityAgent:
    enabled: true
  serviceMonitoring:
    enabled: true
  networkMonitoring:
    enabled: true
