api:
  key: ""
datadog:
  apiSecret:
    secretName: datadog-secret

  apm:
    instrumentation:
      enabled: true
  logs:
    enabled: true
    containerCollectAll: true
  securityAgent:
    enabled: true
  serviceMonitoring:
    enabled: true
  networkMonitoring:
    enabled: true
