datadog-operator:
  apiKey: "s"
datadog:
  apiSecret:
    operatorSecretName: monitoring-datadog-operator-apikey
    secretName: datadog-secret
  logs:
    enabled: true
    containerCollectAll: true
  securityAgent:
    enabled: true
  serviceMonitoring:
    enabled: true
  networkMonitoring:
    enabled: true
