{{- range .Values.runners }}
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: {{ include "ci-runners.fullname" $ }}-runners
spec:
  template:
    spec:
      organization: {{ .org }}
      securityContext:
        #All level/role/type/user values will vary based on your SELinux policies.
        #See https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux_atomic_host/7/html/container_security_guide/docker_selinux_security_policy for information about SELinux with containers
        seLinuxOptions:
          level: "s0"
          role: "system_r"
          type: "super_t"
          user: "system_u"
      ephemeral: true
      dockerdWithinRunnerContainer: true
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: {{ include "ci-runners.fullname" $ }}-runners-{{ .org }}-autoscaler
spec:
  minReplicas: {{ .min }}
  maxReplicas: {{ .max }}
  scaleTargetRef:
    name: {{ include "ci-runners.fullname" $ }}-runners
    # Uncomment the below in case the target is not RunnerDeployment but RunnerSet
    #kind: RunnerSet
  scaleUpTriggers:
  - githubEvent:
      checkRun:
        types: ["created"]
        status: "queued"
        # Optionally restrict autoscaling to being triggered by events from specific repositories within your organization still
        # repositories: ["myrepo", "myanotherrepo"]
    amount: 1
    duration: "5m"
{{- end }}
