{{- range .Values.runners }}
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: {{ include "ci-runners.fullname" $ }}-runners
spec:
  template:
    spec:
      organization: {{ .org }}
      ephemeral: true
      containers:
      - name: runner
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          privileged: true

---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: {{ include "ci-runners.fullname" $ }}-runners-{{ .org }}-autoscaler
spec:
  minReplicas: {{ .min }}
  maxReplicas: {{ .max }}
  scaleTargetRef:
    name: {{ include "ci-runners.fullname" $ }}-runners
    # Uncomment the below in case the target is not RunnerDeployment but RunnerSet
    #kind: RunnerSet
  scaleUpTriggers:
  - githubEvent:
      checkRun:
        types: ["created"]
        status: "queued"
        # Optionally restrict autoscaling to being triggered by events from specific repositories within your organization still
        # repositories: ["myrepo", "myanotherrepo"]
    amount: 1
    duration: "5m"
{{- end }}
