grafana_prometheus_username: ""
grafana_password: ""

kube-prometheus-stack:
  alertmanager:
    enabled: true
  grafana:
    enabled: true
  prometheus:
    prometheusSpec:
      remoteWrite:
      - url: https://prometheus-blocks-prod-us-central1.grafana.net/api/prom/push
        basicAuth:
            username:
              name: kubepromsecret
              key: username
            password:
              name: kubepromsecret
              key: password
  prometheusOperator:
    admissionWebhooks:
      certManager:
        enabled: false
        issuerRef:
          name: "letsencrypt-prod"
          kind: "ClusterIssuer"
