grafana_prometheus_username: ""
grafana_password: ""

grafana:
  github_auth: ""
kube-prometheus-stack:
  alertmanager:
    enabled: true
  grafana:
    enabled: true
    extraConfigmapMounts:
      - name: monitoring-grafana-gitub-auth
        mountPath: /etc/grafana/monitoring-grafana-gitub-auth.ini
        configMap: monitoring-grafana-gitub-auth
        subPath: monitoring-grafana-gitub-auth.ini
    ingress:
      enabled: true
      ingressClassName: networking-traefik
      annotations:
        external-dns.alpha.kubernetes.io/hostname: ""
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/service.serversscheme: http
        traefik.ingress.kubernetes.io/router.entrypoints: websecure-tsnet
        traefik.ingress.kubernetes.io/router.tls: "true"
      hosts:
        - grafana.i.unerror.network
      tls:
        - hosts:
            - grafana.i.unerror.network
          secretName: grafana-ingress-tls
  prometheus:
    prometheusSpec:
      storageSpec:
        volumeClaimTemplate:
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 50Gi
  prometheusOperator:
    admissionWebhooks:
      certManager:
        enabled: false
        issuerRef:
          name: "letsencrypt-prod"
          kind: "ClusterIssuer"
