{{- if .Values.server.tls.enabled -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "chatbox.fullname" . }}-cert
  labels:
    {{- include "chatbox.labels" . | nindent 4 }}
    use-cloudflare-solver: {{ .Values.server.tls.dns01 }}
spec:
  secretName: {{ include "chatbox.fullname" . }}-crt-secret
	{{- with .Values.server.tls.hostnames }}
  dnsNames:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.server.tls.issuerRef }}
  issuerRef:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}