apiVersion: v1
kind: Service
metadata:
  name: {{ include "chatbox.fullname" . }}-chatbox-metrics
  labels:
    {{- include "chatbox.labels" . | nindent 4 }}
  {{- with .Values.irc.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/instance: chatbox
    app.kubernetes.io/name: matrix-synapse
