apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: chatbox
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: chatbox
      app.kubernetes.io/name: matrix-synapse
  podMetricsEndpoints:
  - port: "9090"
    path: /_synapse/metrics

