apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "chatbox.fullname" . }}-metrics-generic-worker
  labels:
    {{- include "chatbox.labels" . | nindent 4 }}
  {{- with .Values.irc.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: chatbox
      app.kubernetes.io/name: matrix-synapse
  podMetricsEndpoints:
    - port: metrics
      path: /_synapse/metrics
  namespaceSelector:
    matchNames:
    - default