apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chatbox.fullname" . }}-config
  labels:
    {{- include "chatbox.labels" . | nindent 4 }}

data:
  ircd.motd: |
    👋
{{ .Files.Get "config/ircd.motd" | indent 4 }}
  ircd.yaml: |
    # Configuration
{{ .Files.Get "config/ircd.yaml" | indent 4 }}

