apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chatbox.fullname" . }}-config
  labels:
    {{- include "chatbox.labels" . | nindent 4 }}

data:
  ircd.motd: |-
      {{ .Files.Get "ircd.motd" | indent 2 }}
  ircd.yaml: {{ range .Files.Lines "ircd.yaml" }}
    {{ . }} {{ end }}
