apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chatbox.fullname" . }}-config
  labels:
    {{- include "chatbox.labels" . | nindent 4 }}

data:
  ircd.conf: {{- toYaml .Values.server.config | nindent 4 }}