{{- if .Values.ingress.enabled -}}
{{- $fullName := include "chatbox.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "chatbox.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-ssl-secret: {{ include "chatbox.fullname" . }}-crt-secret
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      secretName: {{ include "chatbox.fullname" . }}-crt-secret
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ include "chatbox.fullname" . }}-ircd
              servicePort: 443
  {{- end }}
