apiVersion: v1
kind: Service
metadata:
  name: {{ include "chatbox.fullname" . }}-ircd
  labels:
    {{- include "chatbox.labels" . | nindent 4 }}
  {{- with .Values.irc.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.irc.service.port }}
      targetPort: 6667
      protocol: TCP
      name: irc
    {{- if .Values.irc.server.tls.enabled }}
    - port: 443
      name: websockets  
      targetPort: 443
    - port: {{ .Values.irc.service.tlsPort }}
      targetPort: 6697
      protocol: TCP
      name: ircs
    {{- end }}
  selector:
    {{- include "chatbox.selectorLabels" . | nindent 4 }}