apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "chatbox.fullname" . }}-new-db
  labels:
    {{- include "chatbox.labels" . | nindent 4 }}
spec:
	{{- with .Values.irc.newpvc.accessModes }}
  accessModes:
    {{- toYaml . | nindent 4 }}
	{{- end }}
  resources:
    requests:
      storage: {{ .Values.irc.newpvc.size }}
  storageClassName: s3-default