apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ include "chatbox.fullname" . }}-irc-tcp
spec:
  entryPoints:
    - irc
  routes:
    - match: HostSNI(`*`)
      services:
        - name: {{ include "chatbox.fullname" . }}-ircd
          port: irc
          terminationDelay: 1000
          proxyProtocol:
            version: 1
---
{{- if .Values.irc.server.tls.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ include "chatbox.fullname" . }}-ircs-tcp
spec:
  entryPoints:
    - ircs
  routes:
    - match: HostSNI(`*`)
      services:
        - name: {{ include "chatbox.fullname" . }}-ircd
          port: ircs
          terminationDelay: 1000
          proxyProtocol:
            version: 1
  tls:
    passthrough: true
{{- end }}
