apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chatbox.fullname" . }}
  labels:
    {{- include "chatbox.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.irc.replicaCount }}
  selector:
    matchLabels:
      {{- include "chatbox.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.irc.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "chatbox.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.irc.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.irc.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.irc.securityContext | nindent 12 }}
          image: "{{ .Values.irc.image.repository }}:{{ .Values.irc.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.irc.image.pullPolicy }}
          ports:
            - name: irc
              containerPort: 6667
              protocol: TCP
            - containerPort: 443
              name: websocket
            {{- if .Values.irc.server.tls.enabled }}
            - name: ircs
              containerPort: 6697
              protocol: TCP 
            {{- end }}
          livenessProbe:
            tcpSocket:
              port: irc
            timeoutSeconds: 5
            periodSeconds: 60
          readinessProbe:
            tcpSocket:
              port: irc
            timeoutSeconds: 5
            periodSeconds: 60
          resources:
            {{- toYaml .Values.irc.resources | nindent 12 }}
          volumeMounts:
          - mountPath: /ircd/
            name: irc-config
            readOnly: true
          - mountPath: /ircd/tls
            name: irc-certs
            readOnly: true
          - mountPath: /ircd/db
            name: irc-db
        - name: config-reloader
          # image is based on busybox which includes inotifyd + pkill
          image: "{{ .Values.irc.image.repository }}:{{ .Values.irc.image.tag | default .Chart.AppVersion }}"
          command: ["/bin/sh"]
          args:
          - "-c"
          - |
            echo "Watching /ircd/";
            inotifyd - /ircd/:wMymndox /ircd/tls/:wMymndox | while read -r notifies ; do
              echo "$notifies";
              echo "notify received, sending SIGHUP";
              pkill -HUP ergo;
            done
            echo "Exiting.";
          volumeMounts:
          - mountPath: /ircd/
            name: irc-config
            readOnly: true
          - mountPath: /ircd/tls
            name: irc-certs
            readOnly: true
      volumes:
      - name: irc-config
        configMap:
          name: {{ include "chatbox.fullname" . }}-config
      - name: irc-certs
        secret:
          secretName: {{ include "chatbox.fullname" . }}-crt-secret
      - name: irc-db
        persistentVolumeClaim:
          claimName: {{ include "chatbox.fullname" . }}-new-db
      {{- with .Values.irc.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.irc.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.irc.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
