apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ include "chatbox.fullname" . }}-ircd-tcp
spec:
  entryPoints:
    - irc
    - ircs
  routes: 
    - match: HostSNI(`*`)
      services:
        - name: {{ include "chatbox.fullname" . }}-ircd
          port: irc
          terminationDelay: 1000
          proxyProtocol:
            version: 2
        {{- if .Values.irc.server.tls.enabled }}
        - name: {{ include "chatbox.fullname" . }}-ircd
          port: ircs
          terminationDelay: 1000
          proxyProtocol:
            version: 2
        {{- end }}
