{{- if .Values.irc.ingress.enabled -}}
{{- $fullName := include "chatbox.fullname" . -}}
{{- $svcPort := .Values.irc.service.port -}}
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: {{ $fullName }}-transport
spec:
    serverName: {{ first .Values.irc.ingress.hosts }}
    certificatesSecrets:
      - {{ $fullName }}-crt-secret
---
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "chatbox.labels" . | nindent 4 }}
  {{- with .Values.irc.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.irc.ingress.ingressClassName }}
  tls:
    - secretName: {{ $fullName }}-crt-secret
  rules:
    {{- range .Values.irc.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}-ircd
                port:
                  number: 443
    {{ end }}
  {{- end }}
