{{ $signkey := index .Values "matrix-synapse" "signingkey" "secret" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chatbox.fullname" . }}-matrix-signkey
data:
	{{- with $signkey }}
  signing.key: {{ . | b64enc }}
	{{- end }}