---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "chatbox.fullname" . }}-db
  labels:
    {{- include "chatbox.labels" . | nindent 4 }}
spec:
	{{- with .Values.pvc.accessModes }}
  accessModes:
    {{- toYaml . | nindent 4 }}
	{{- end }}
  resources:
    requests:
      storage: {{ .Values.pvc.size }}
