apiVersion: v1
kind: Service
metadata:
  name: {{ include "chatbox.fullname" . }}-ircd
  labels:
    {{- include "chatbox.labels" . | nindent 4 }}
    {{- with .Values.server.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "chatbox.selectorLabels" . | nindent 4 }}
  type: NodePort