apiVersion: v2
name: networking
description: Root Kubernetes networking chart
type: application
version: 0.1.1
appVersion: "0.0.15"

dependencies:
  - name: coturn
    version: 0.0.1
    repository: https://savercorp.github.io/helm-charts/
  - name: traefik
    version: 29.0.1
    repository: https://helm.traefik.io/traefik
  - name: webdav
    repository: https://danuk.github.io/k8s-webdav/
    version: 0.0.7
