apiVersion: v2
name: networking
description: Root Kubernetes networking chart
type: application
version: 0.1.1
appVersion: "0.0.15"

dependencies:
  - name: tailscale-relay
    version: 0.0.14
    repository: https://charts.visonneau.fr/
  - name: coturn
    version: 1.1.1
    repository: https://iits-consulting.github.io/coturn-chart/
