doRegistryToken: ENC[AES256_GCM,data:PHK9HY25Lhd7qwAcnGz27/PIXlTl5F/FbIwcfom28OKJCTdVcMLNowY2oCRSNZafOm+FvH3KdLNcrzIPkBmyxIRkNkFc38b8KpBzjJVuiZBdFWA18lEXaVVbWMxMTQJIGRL4ke8spObWXwCdt96YerLWBC+lByRaT2+5O0V0HhKzzaeECLXKX9S1KlTUzeH1Trwd72tX4rW2czYMNLdlgljXq985quU/YYD8yKvBsvH4LElCBvKcMXAySTjNIDW3jBtvypobKHP6KbKFrKKvxBKk16RKz7TDdkALsttoQ4Y=,iv:+85aWLZuD5Ij9TOONpF0116W0EmhmgsdwcVD7x8LF9A=,tag:aQmnrtN3YeQkf4tPlni28g==,type:str]
tailscale:
    relay:
        authKey: ENC[AES256_GCM,data:CBzLIWJQbs7SoITBjSlfe76Rasb3ylcwhql7iamMDu6c72zM+RPLxw==,iv:IziLkER84PDKchKZwp+e/B5fMz59eML1shrmKBEtNXk=,tag:DalU41IlTUByBPoXQfiyYw==,type:str]
    traefik:
        authKey: ENC[AES256_GCM,data:DAX5Ft5fGitZ+Q/jUwcZANNrN11zASOqnEI/xSLNsq7AK85+MsnbMmE=,iv:LkB4OUUwsb7055ml8hBL/3DmYoy2it3noOhLw8r5lZs=,tag:wWpFjUR2XsU4oPukYVnGnA==,type:str]
coturn:
    config:
        turnserver: ENC[AES256_GCM,data:Io0B4jEjggmI9xXTGNLC3XMA7w7ZToNNRlHm6DqDGLocXJTVOJN1jg4fQsskvekd1HjOwRIzkV2XDSZc1iF2yJe0G5wNSBt2Mj4W1ivoUpHvXu20WdnGAPybBWA8pf9y0OXDFmhx0CKI0WPFYnQrRDzYzuqwbllZ45M5KPDrde1MnxHoM+nDI/kib1lawPpOE2zDKxYD5heD/TIHIWAWpuVkmG/5j6WAFV3wH+PH7stZlmR6Am0XLTHrM8Y6yFBc4hew6dW5F+el3HCAbC/vOGU3yc5OPUCTPSC4lp/nbtCE6d2RbAOhZpln6O3nOF3BLwI64QwYUsY0lhfTouhv4EWwqS6lqzrRtK642Fw1NSfffe4h75Y2z9Ph4fJLMwPDXGRssgzrZnXIqu9alpI4R0ODN9opo9LnbvQW02Kvx5DS7q1pJBTWe/QGDGb3d+kiiV9VHZV1tc9/mZwVCexUcp6cmsvoip/yGsK7sMeMXjUTybddMGYf9ovsGm7KVvXh0BDbA6ClyPYaIH1E9domnJDuHkwArsQNLsyfQdRe7AOftTm7FfXI+50+bpcm9PcWrlhVVabMd8JicVe70w==,iv:MZrG4I+Kjx/B34J52eC1vMQxESgntr0UpyUI6nOL9Do=,tag:KmmMNSo3sTldPiuKhRoDlw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a7dumefn2xmd2rqenrldhlqzqedpepnp90e94trzu7eh6xp4hu4qzmv8cq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArOXpLaGMyRm1jUEhCbDRa
            RGRaY1o3NTZlUkR0b2cyTjVrRGRqT3ErdVhNCldweVRSTFRjWlEvVGdLK1pTZ3pj
            OFJvN2NDWlpGTWxudlB0TXBhY2RGODgKLS0tIGMwNUtFS0F3T2w2cSs1aGFZY2FK
            bkpwY1NGaVQyVnpsQzQvU2k0ZWlKazgKds5QwCVsK3ai5t04TmLMkrwCS+4mib5G
            zHRm8EyEqQzGXHm58aEtdnsYn/bZXOYuW1vh1A2qCv4sq39ipqEgUA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zn9hyvar0dv75pvd9e4qkj549ltt3n0t9vwgkptrm0etphrhl3vshp6rd9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlM2tIZEljNmQ4bE5rRHZk
            d1JCNjE3YXJGMHN5b1BheEFXbVBuS1IwdFc4CkpYWTZGTjBnTHNnR2YxT0NiUlRL
            VUpwbmFzQVJSSEUyTnh6ZGVDQ3dLTE0KLS0tIEFuZzZwaGRBd0hHQURYYkZUbXM3
            M1YxVFVWWjU2ZHdyWTRndDk0d3ZUbzAKw+8M/BCkM4bTAbyOC7tWS1+Ar0orRRdV
            LL0FtCrT7AesY2B5BCTTuaMXXUBQ5zat8QPMsIWniYU+/DQazxUtpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-04T22:30:30Z"
    mac: ENC[AES256_GCM,data:ofY1hldBfpk/QDA0oa1adnwAe3lPTNJNg40j/HqcQHUGx9FXSbcpw9tDKKIC61QsU6EM3faFVV9/vX57ohH/qR1NZIrpSTpL2m7TBo/hH022N1TrAJHfUjEYYs9Tn5FmDkeQZa9jprjGNXcQzzxR3c1nGrk7MvFf0a3+Y5SUdvA=,iv:/B7YfDS4gVW5+7SCxah5PLLWIu0AB5s9jVwLLd28Mfo=,tag:qvZ56kkRPwqHwXU0FMreDg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
