tailscale-relay:
  config:
    variables:
      TAILSCALE_ADVERTISE_ROUTES: 10.0.0.0/8
      TAILSCALE_ADVERTISE_TAGS: tag:une-k8s
      TAILSCALE_HOSTNAME: "une-k8s-relay"

coturn:
  coturn:
    service:
      type: ClusterIP
    image:
      tag: "4.5.2"

tls:
  enabled: true
  hostnames:
    - turn.unerror.network
    - turn.unerror.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io

ingress:
  enabled: true
  annotations:
    external-dns.alpha.kubernetes.io/target: lb.unerror.network
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
  ingressClassName: nginx
  hosts:
    - turn.unerror.com
    - turn.unerror.network

traefik:
  deployment:
    replicas: 2
  ingressClass:
    enabled: true
    fallbackApiVersion: "v1"
  providers:
    kubernetesCRD:
      allowCrossNamespace: true
      allowExternalNameServices: true
    kubernetesIngress:
      publishedService:
        enabled: true
  logs:
    access:
      enabled: true
  additionalArguments:
    - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
    - "--entryPoints.irc.proxyProtocol.trustedIPs=127.0.0.1/32,10.0.0.0/8"
    - "--entryPoints.ircs.proxyProtocol.trustedIPs=127.0.0.1/32,10.0.0.0/8"
  ports:
    irc:
      port: 6667
      exposedPort: 6667
      protocol: TCP
      expose: true
    ircs:
      port: 6697
      exposedPort: 6697
      protocol: TCP
      expose: true
  service:
    annotations:
      service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"
      external-dns.alpha.kubernetes.io/hostname: lb-trfk.unerror.network
      external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
