tailscale-relay:
  config:
    variables:
      TAILSCALE_ADVERTISE_ROUTES: 10.0.0.0/8
      TAILSCALE_ADVERTISE_TAGS: tag:une-k8s
      TAILSCALE_HOSTNAME: "une-k8s-relay"

coturn:
  coturn:
    service:
      type: ClusterIP
    image:
      tag: "4.5.2"

tls:
  enabled: true
  hostnames:
    - turn.unerror.network
    - turn.unerror.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io

ingress:
  enabled: true
  annotations:
    external-dns.alpha.kubernetes.io/target: lb.unerror.network
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
  ingressClassName: nginx
  hosts:
    - turn.unerror.com
    - turn.unerror.network

traefik:
  ingressClass:
    enabled: true
  providers:
    kubernetesCRD:
      allowCrossNamespace: true
      allowExternalNameServices: true
  logs:
    access:
      enabled: true
  service:
    annotations:
      service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"
