tailscale:
  replicas: 1
  image:
    repository: registry.digitalocean.com/une-k8s/networking/tailscale
    tag: v1.22.1
  imagePullSecrets:
    - name: do-docker-registry
  secret: networking-tailscale-auth-relay
  state: networking-tailscale-state
  additionalStates:
    - networking-tailscale-state-traefik-sidecar
  serviceAccount: tailscale
  additionalserviceAccountBindings:
    - networking-traefik
  proxy:
    enabled: true
    env:
      - name: USERSPACE
        value: "false"
      - name: DEST_IP
        value: 10.118.0.0/20
      - name: ROUTES
        value: 10.0.0.0/8,10.118.0.0/20
      - name: EXTRA_ARGS
        value: "--hostname une-k8s-relay --advertise-tags=tag:une-k8s --snat-subnet-routes=true --netfilter-mode=on"

doRegistryToken: ""

coturn:
  coturn:
    traefik:
      tcp:
        entrypoint: turn-tcp
    service:
      type: ClusterIP
    image:
      tag: "4.5.2"

traefik:
  # todo: when DO supports Dualstack IPv4/IPv6 kubelets, remove this and use tailnet IPv6 as the
  # ExternalIP on a Service
  dashboard:
    hosts:
      - traefik.i.unerror.network
    tls:
      enabled: true
      secretName: networking-traefik-cert
      issuerRef:
        name: letsencrypt-prod
        kind: ClusterIssuer
  securityContext:
    runAsUser: 0
    runAsNonRoot: false
    privileged: true
  deployment:
    replicas: 3
    imagePullSecrets:
      - name: do-docker-registry
    kind: Deployment
    additionalContainers:
      - name: tailscale-sidecar
        image: registry.digitalocean.com/une-k8s/networking/tailscale:v1.22.1
        env:
          - name: KUBE_SECRET
            value: networking-tailscale-state-traefik-sidecar
          - name: USER_SPACE
            value: "false"
          - name: EXTRA_ARGS
            value: "--hostname=une-k8s-traefik --advertise-tags=tag:une-k8s --snat-subnet-routes=true --netfilter-mode=on"
          - name: AUTH_KEY
            valueFrom:
              secretKeyRef:
                name: networking-tailscale-auth-traefik
                key: AUTH_KEY
                optional: true
  ingressClass:
    enabled: true
    fallbackApiVersion: "v1"
    isDefaultClass: true
  providers:
    kubernetesCRD:
      allowCrossNamespace: true
      allowExternalNameServices: true
    kubernetesIngress:
      publishedService:
        enabled: true
  logs:
    access:
      enabled: true
  additionalArguments:
    - "--entryPoints.web.proxyProtocol.trustedIPs=127.0.0.1/32,10.0.0.0/8"
    - "--entryPoints.websecure.proxyProtocol.trustedIPs=127.0.0.1/32,10.0.0.0/8"
    - "--entryPoints.irc.proxyProtocol.trustedIPs=127.0.0.1/32,10.0.0.0/8"
    - "--entryPoints.ircs.proxyProtocol.trustedIPs=127.0.0.1/32,10.0.0.0/8"
    - "--entryPoints.turn-tcp.proxyProtocol.trustedIPs=127.0.0.1/32,10.0.0.0/8"
    - "--entryPoints.web-tsnet.address=[::]:80"
    - "--entryPoints.web-tsnet.http.redirections.entryPoint.to=websecure-tsnet"
    - "--entrypoints.web-tsnet.http.redirections.entryPoint.scheme=https"
    - "--entryPoints.websecure-tsnet.address=[::]:443"
    - "--entryPoints.webwebsecure-tsnet.http.tls=true"
  tlsOptions:
    default:
      preferServerCipherSuites: true
      minVersion: VersionTLS11
  ports:
    irc:
      name: irc
      port: 6667
      exposedPort: 6667
      protocol: TCP
      expose: true
    ircs:
      name: ircs
      port: 6697
      exposedPort: 6697
      protocol: TCP
      expose: true
    turn-tcp:
      name: turn-tcp
      port: 3478
      exposedPort: 3478
      protocol: TCP
      expose: true
    web:
      name: web
      nodePort: 32080
      redirectTo: websecure
    websecure:
      name: websecure
      nodePort: 32443
      tls:
        enabled: true
    metrics:
      name: metrics
      port: 9100
      expose: false
      exposedPort: 9100
      protocol: TCP
  service:
    annotations:
      service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"
      external-dns.alpha.kubernetes.io/hostname: lb-trfk.unerror.network
      external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
