tailscale-relay:
  config:
    variables:
      TAILSCALE_ADVERTISE_ROUTES: 10.0.0.0/8
      TAILSCALE_ADVERTISE_TAGS: tag:une-k8s
      TAILSCALE_HOSTNAME: "une-k8s-relay"

coturn:
  coturn:
    traefik:
      tcp:
        entrypoint: turn-tcp
    service:
      type: ClusterIP
    image:
      tag: "4.5.2"

traefik:
  deployment:
    kind: DaemonSet
  ingressClass:
    enabled: true
    fallbackApiVersion: "v1"
    isDefaultClass: true
  providers:
    kubernetesCRD:
      allowCrossNamespace: true
      allowExternalNameServices: true
    kubernetesIngress:
      publishedService:
        enabled: true
  logs:
    access:
      enabled: true
  additionalArguments:
    - "--entryPoints.web.proxyProtocol.trustedIPs=127.0.0.1/32,10.0.0.0/8"
    - "--entryPoints.websecure.proxyProtocol.trustedIPs=127.0.0.1/32,10.0.0.0/8"
    - "--entryPoints.irc.proxyProtocol.trustedIPs=127.0.0.1/32,10.0.0.0/8"
    - "--entryPoints.ircs.proxyProtocol.trustedIPs=127.0.0.1/32,10.0.0.0/8"
    - "--entryPoints.turn-tcp.proxyProtocol.trustedIPs=127.0.0.1/32,10.0.0.0/8"
  tlsOptions:
    default:
      preferServerCipherSuites: true
      minVersion: VersionTLS11
  ports:
    irc:
      port: 6667
      exposedPort: 6667
      protocol: TCP
      expose: true
    ircs:
      port: 6697
      exposedPort: 6697
      protocol: TCP
      expose: true
    turn-tcp:
      port: 3478
      exposedPort: 3478
      protocol: TCP
      expose: true
    web:
      port: 80
      nodePort: 32080
      redirectTo: websecure
    websecure:
      port: 443
      nodePort: 32443
      tls:
        enabled: true
  service:
    annotations:
      service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"
      external-dns.alpha.kubernetes.io/hostname: lb-trfk.unerror.network
      external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
