tailscale-relay:
  config:
    variables:
      TAILSCALE_ADVERTISE_ROUTES: 10.0.0.0/8
      TAILSCALE_ADVERTISE_TAGS: tag:une-k8s
      TAILSCALE_HOSTNAME: "une-k8s-relay"

coturn:
  coturn:
    service:
      type: ClusterIP
      annotations:
        external-dns.alpha.kubernetes.io/target: lb.unerror.network
        external-dns.alpha.kubernetes.io/hostname: turn.unerror.network
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
    image:
      tag: "4.5.2"
    config: |
      realm=turn-domain.de
      log-file=stdout
      pidfile=/var/tmp/turnserver.pid
      userdb=/var/tmp/turnserver.db
      # Specify the user for the TURN authentification
      # Enable long-term credential mechanism
      lt-cred-mech
      user=Username:Password
      no-cli
      no-tls
      no-dtls
      verbose
      prod

tls:
  enabled: true
  hostnames:
    - turn.unerror.network
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
