apiVersion: v1
kind: Secret
metadata:
  name: {{ include "base.fullname" . }}-postgres-ca-cert
type: Opaque
data:
  # You can include additional key value pairs as you do with Opaque Secrets
  crt: {{ index .Values "postgres-ca-cert" | b64enc}}
