apiVersion: v1
kind: Secret
metadata:
  name: postgres-ca-cert
  namespace: default
type: Opaque
data:
  # You can include additional key value pairs as you do with Opaque Secrets
  db-ca.crt: {{ index .Values "postgres-ca-cert" | b64enc}}
