apiVersion: v2
name: chatbox
description: A Helm chart for Kubernetes
type: application
version: 0.1.2
appVersion: "latest"

dependencies:
  - name: ma1sd
    version: 0.1.5
    repository: file://./vendor/ma1sd/
  - name: matrix-synapse
    repository: https://ananace.gitlab.io/charts/
    version: 2.1.12
