apiVersion: v2
name: chatbox
description: A Helm chart for Kubernetes
type: application
version: 0.1.2
appVersion: "latest"

dependencies:
  - name: ma1sd
    version: 0.1.6
    repository: file://./vendor/ma1sd/
  - name: matrix-synapse
    repository: https://ananace.gitlab.io/charts/
    version: 2.1.14
  - name: element-web
    repository: https://ananace.gitlab.io/charts/
    version: 1.0.38
  - name: matrix-appservice-irc
    repository: file://./vendor/matrix-appservice-irc
    version: 0.1.16
  - name: mautrix-hangouts
    repository: https://halkeye.github.io/helm-charts/
    version: 0.1.6
