apiVersion: v2
name: chatbox
description: A Helm chart for Kubernetes
type: application
version: 0.1.2
appVersion: "latest"

dependencies:
  - name: ma1sd
    version: 0.1.6
    repository: file://./vendor/ma1sd/
  - name: matrix-synapse
    repository: https://ananace.gitlab.io/charts/
    version: 2.1.33
  - name: element-web
    repository: https://ananace.gitlab.io/charts/
    version: 1.1.9
  - name: matrix-appservice-irc
    repository: file://./vendor/matrix-appservice-irc
    version: 0.1.16
