apiVersion: v2
name: chatbox
description: A Helm chart for Kubernetes
type: application
version: 0.1.2
appVersion: "latest"

dependencies:
  - name: ma1sd
    version: 0.2.1
    repository: https://netsoc.github.io/charts/
