apiVersion: v2
name: chatbox
description: A Helm chart for Kubernetes
type: application
version: 0.1.3
appVersion: "latest"

dependencies:
  - name: matrix-synapse
    repository: https://ananace.gitlab.io/charts/
    version: 3.9.12
  - name: sliding-sync-proxy
    repository: https://ananace.gitlab.io/charts/
    version: 0.2.13
  - name: element-web
    repository: https://ananace.gitlab.io/charts/
    version: 1.3.32
  - name: matrix-appservice-irc
    repository: file://./vendor/matrix-appservice-irc
    version: 0.2.0
  - name: matrix-meetings-bot
    repository: file://./vendor/matrix-meetings/charts/matrix-meetings-bot/
    version: 0.1.0
  - name: matrix-meetings-widget
    repository: file://./vendor/matrix-meetings/charts/matrix-meetings-widget/
    version: 0.1.0
