apiVersion: v2
name: chatbox
description: A Helm chart for Kubernetes
type: application
version: 0.1.3
appVersion: "latest"

dependencies:
  - name: ma1sd
    version: 0.1.6
    repository: file://./vendor/ma1sd/
  - name: matrix-synapse
    repository: https://ananace.gitlab.io/charts/
    version: 3.7.0
  - name: sliding-sync-proxy
    repository: https://ananace.gitlab.io/charts/
    version: 0.2.4
  - name: element-web
    repository: https://ananace.gitlab.io/charts/
    version: 1.2.10
  - name: matrix-appservice-irc
    repository: file://./vendor/matrix-appservice-irc
    version: 0.2.0
