apiVersion: v2
name: chatbox
description: A Helm chart for Kubernetes
type: application
version: 0.1.2
appVersion: "latest"

dependencies:
  - name: ma1sd
    version: 0.1.3
    repository: file://../ma1sd/
  - name: coturn
    version: 1.1.1
    repository: https://iits-consulting.github.io/coturn-chart/
