irc:
    server:
        oper:
            orcam:
                class: ENC[AES256_GCM,data:tTfDSykX+Pb47kba,iv:oRRx3xk8dKi4ycjb8nKhLMGNvzz6V8j/o17CJAj+R/Q=,tag:FnleqBeRaYgFgMJ98RPt5w==,type:str]
                whois-line: ENC[AES256_GCM,data:XE/UJ28EUhmrh+GQPOeLE9nZ7w==,iv:LBSGzn+CpvIpo4IS1H1e+jnIkBfGWRvH9UuZd7dV8JY=,tag:5Xwq124nnE7GNzZPT4Xp/g==,type:str]
                vhost: ENC[AES256_GCM,data:vRuz46bvdUsYRXziDRRqjSoxhZ4=,iv:lU9ZelP5ULDZiCH6MA+zsIplnqNLBJCneBcEiqzfmE4=,tag:1s2hH2kGppADpbH/Pozuyg==,type:str]
                hidden: ENC[AES256_GCM,data:5WUm1xI=,iv:8Mx+QhW9Qs6aSu7DO5fqo2rLIli38OH9xsAoHnqrwJ8=,tag:+FWpmml4+hsaiDamrxK2JQ==,type:bool]
                modes: ENC[AES256_GCM,data:jadsYo1Jt6m6Nuo317JvjQ==,iv:JtPvXegMu5Fcep70Com3I7M0JxUACXIu7IMfy732tpk=,tag:+9vVNhKx8kdpX/zpbMDDzw==,type:str]
                password: ENC[AES256_GCM,data:baeJ9k80yrCTYvlc5XNp1T0QDvUHzvGrUt/bnQcphRUZJbSxp6u9eRnU/UxRdWPbvGFDQ4/DwHJfv/cc,iv:M6M+k0BakPwh8jRPOo3C49L3bvjCco0ZkeLrHDiJZOg=,tag:eJhIeg9f/+mKZcJjhFoM6Q==,type:str]
            Striek:
                class: ENC[AES256_GCM,data:6rAF/nD4Q40Ytx5x,iv:3IKUPiZWd5clkLL8nwg/l445enUK8Vqso9lnVaL0KXs=,tag:3WbCjqtlaREexbuXenBoOQ==,type:str]
                whois-line: ENC[AES256_GCM,data:CTib0zpe+hU4XVfWTQN7w7lrEB2j11noRnfFQG7Lh8n2/bJfptsTlZ5TAg==,iv:gREUwvawGT0cFyrbsD+PCTg8FDOkoJSkqI4Cfhw4mA4=,tag:yBSrjgd+aqh5XmS1XyXKcA==,type:str]
                vhost: ENC[AES256_GCM,data:yh3DmKLFbPrL3T2r52oc+bwAPg==,iv:4TZYMXe4HEhi51PfV/o9tulmN3nh9mpsSQ6BrHnwGYM=,tag:NtyLHLiW9LksxNpdhDJYxA==,type:str]
                hidden: ENC[AES256_GCM,data:uG8FVEM=,iv:vp0MtP0SqQuHc0CJhXLvSJ4QbN9/ZvFt4+DI+rFVpDE=,tag:Xothjpiczr/3sOP7vzlYYQ==,type:bool]
                modes: ENC[AES256_GCM,data:WAqmQXFEZAvpEjwiSqIyJw==,iv:JA6TRVOiF6/bcP3yRHBMSd9CA6MUy+VuA8LQPMfyArM=,tag:5vHsr9pts4pVC0itmMlEYg==,type:str]
                password: ENC[AES256_GCM,data:0jivD1E6PjaW3XghWY0Jteyl6xyhH15ldRJGTtioBNt9KKoYdJL1CM55oWk4zaMzf2ctKjGOK57qKJh2,iv:kuGYz3Bd9Imxoyaw4uOLLlHhTJWucgCM38PrT0htzWY=,tag:LSBEiCFoxuRHAtiQ5GduIA==,type:str]
ma1sd:
    signing_key:
        seriel: ENC[AES256_GCM,data:7wrsKFJLvJLyXq4D,iv:HlYreS2dISc8MGLyeb/BzK0kC2SzANn09Z8Ex1iyQjw=,tag:sWINGhFl9WFoDY5yJN+ZuA==,type:str]
        algo: ENC[AES256_GCM,data:1WOEP97IhA==,iv:55AzLH4YnaEVdD2eGcWxWJaZ9SHG5QAjiaR/MJJK66s=,tag:SfkfAaV/d+yenIbxr4TP5Q==,type:str]
        value:
            version: ENC[AES256_GCM,data:mA==,iv:lC0GXt8Ks6CQIk7gRYdfMSAviJHOzQfZMEdCkydce5Q=,tag:HBMWyVg3DV4dm9zdj4sILw==,type:str]
            is_valid: ENC[AES256_GCM,data:oI3BQA==,iv:t4Cz1xbd+JVSm3WjEV4en68teizkpiS6Xm4v8MnDAW0=,tag:gzmPUfnR1/B/9MAgPqRDOw==,type:bool]
            key: ENC[AES256_GCM,data:LOXPeei5YTm4OeIXQyazbgOhiHKA/spo11sb4qW1wrsKd3Ivc3l1/gDPxw==,iv:wH9LUzkwj2GngxjqTevmXhNaYlFmcuxCWKfeCrxyjDs=,tag:XA/T6FrcciLb6fPJt7BY/A==,type:str]
    config:
        threepid:
            medium:
                msisdn:
                    connectors:
                        twilio:
                            account_sid: ENC[AES256_GCM,data:ZYLRhTp9VjjAwbdZYPw8AIvtUb7/sLfsBvPdp3osgFnr8w==,iv:BLXYjll8hbKXG3Nh/UWVGqIuZjRsDrv732KlMrbcdUY=,tag:NNVXxRg/B4iPUKujAlPBIA==,type:str]
                            auth_token: ENC[AES256_GCM,data:MhvPMzGdxCFNjTfVOu+cbbYw7zC+FVP6yZRvOZ6KH5w=,iv:w9gkQiU8hYr9pKa5S9CHb0+7Vz0HGg1k5sU0vG6aMpE=,tag:IarxOys7m1ybm1EKcB144Q==,type:str]
                            number: ENC[AES256_GCM,data:B+unQlmH/mNkFL4O,iv:iD02FPzl8cFZYA/MZik5AE5nApW2LmBucueJKsOt/3A=,tag:qIgSUKxOVTekst0lpT2DtQ==,type:str]
                email:
                    connectors:
                        smtp:
                            host: ENC[AES256_GCM,data:vcbqW7u5MVGgLCRDdcaVfY0=,iv:P7IPIIffAXHn6+shiUyczN5vYnEklRFpHIwDijBbBmY=,tag:SY/qWekaTM8ZxY2IwKwa1g==,type:str]
                            login: ENC[AES256_GCM,data:UACNTxEUK2k=,iv:AV9IZEfe/xzeayifO0E6C1DGYgINvWrA/J0WwOeL98A=,tag:oh6PGVdH8cubdE4ITmd4xA==,type:str]
                            password: ENC[AES256_GCM,data:3r0TgEGZ5KDCUzyfwBFvWaCPhH5cT6GmbNxcz7x2Cmb+zAhpN94nHB08jtIw4BFI+oYmvhRGNRjc9xhbqGIecY+wpJXJTZhqbUCaY2VCwb7ahcDK5KJtjlePslec6tEM,iv:mKyLn5Q+1UI/jmnH1BRWKLczxWz8vfPNrb/YbxuVehw=,tag:CiByheeWuycsWibmu9K1ZQ==,type:str]
                            port: ENC[AES256_GCM,data:ZfW/,iv:xVzb3yyYRQxia1C/qS5O8YZmJ7ziAiu5RRs3rFu9TIY=,tag:kVFOijzKVwY5eJO2Znpv9Q==,type:int]
                            tls: ENC[AES256_GCM,data:uw==,iv:w+q3YpdYe4M7Ls8vH5E5VD/tlC7ma/xjMgqjmPPTJI0=,tag:BKFSnMZ5ogQDIADarV3EDw==,type:int]
        storage:
            provider:
                postgresql:
                    database: ENC[AES256_GCM,data:pa+w7ogzD+XNR2gPWGjA5iPjZlImceGeO4Cfqwhm9Qtlgfs8fOGamIzxbUa4UvJ7dr+2/Uu9eLIG2n/Tc2xY8RljtwZpP8qWxQFMCan5SiD9ChCPQ9gQSuvTr5VI,iv:CQ5LaUiyQZwSQ31lFigQPFMQTx3HhvWxM8Azw6hG6Sc=,tag:vykdnIXxvdx9G/mMmfqzOg==,type:str]
                    password: ENC[AES256_GCM,data:b2KrVUd796vI5JNG+wcdMw==,iv:aDjV6+mPi+aeb5o0js06MJR0mOxjJT4ZdRJg+N4ApxM=,tag:Ogdr/lSGt8DLPN5ZBIeN9A==,type:str]
                    username: ENC[AES256_GCM,data:CgZd31kK,iv:dF3pAs2WhUWLNDyDzmhRL6yYfHuDmwZGH8Wqe9xvuM4=,tag:5q7F0TricB68kOdjBy11Sg==,type:str]
        synapseSql:
            connection: ENC[AES256_GCM,data:/wljDTl6HG5Y9edh8Hc8z8cS4v/ybuFaPLZQC6JOZgvRJ+wuODHf0ECkpharf2Tfu9/5az3sO2u8x/GSbK5VJAyXEO2bQNRxCL8C8zmTZbcGhfp0T5NYhSgc+moqw2h8v8wIeyiLPvQ=,iv:cOukbehuj4+jHvWrpptEaD/Gm0ItEBhE98/CcIUi4/w=,tag:MImNhO4X/uRKqj2psmv4cA==,type:str]
        notification:
            handlers:
                sendgrid:
                    api:
                        key: ENC[AES256_GCM,data:DZDJRIOCR7oyyYOHeD1jD0jot6FvHS4Jx0DfSS+vFjYgWOZlZCgjVSCxhw+ZjZDK8YjrT7Hfv9X/LzNMQ2bUnmrsqfK6,iv:q0HIl9PdE0JgCjxoQq6If+hWpb6zSPGpz/ql8nWFbQw=,tag:DrWw7K58zOFmkCgqlQGkEQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a7dumefn2xmd2rqenrldhlqzqedpepnp90e94trzu7eh6xp4hu4qzmv8cq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoelp6bFFhZ3dqSEdlb1JK
            d3BqeUpldkdCZ2QrY1hNSmZCc08zRHFtM0hJCmI0WGlkcEIyTlRMZm9CYXpoQ1lv
            T2dDaCswUHdSVmZvckcxWHkycE5wT0kKLS0tIGNIT0VORzVFWGxqQUdIZ0hpaUdp
            cjB4d05uRmVaQVhqM3ppajhjcVN1dUkKMbYZYqvAGQePXIFe1Qki3ioFQmHFztTp
            h1L/QQzny7y2K4W2mdsiW/nhRoZ8SZ0zNuGEsoaIlBnQ+M9GqRbFMg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zn9hyvar0dv75pvd9e4qkj549ltt3n0t9vwgkptrm0etphrhl3vshp6rd9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMT1c5anUwVkxhSHlJeGRW
            cDZpcEtzaGYzUzVnRGk5cXM5Tk85aXhnQ1hNCjFaL21EN2hIVTNqalYvZWN2ZUFY
            QmVjUm5COTZZKzNMZE9oeTNPTDlEbU0KLS0tIGNxWUtnaktyNHNwQVAxRHgwV2dm
            dWkwdC9ZMnowN2NhdGg5dzl5cmQwR1UKmD6k/vLE6b8z1+/4vOOdaM8hePh8xqbT
            cPbsnADRWQcHvQNPlI1VHxNx581Y/HjCydO4yHHypeWvnipwDGSacA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-10-11T18:13:35Z"
    mac: ENC[AES256_GCM,data:mZrxqjsmnhy/Txnnzjt+TJFIfUlN95ZnT7t/DTEhSzHuqukPsH5rkdsJ7LERDhkBRwBPSOFDicKk48Zi8PZArj9nWA6Zi4UuRv9+eu81zL7qsac/VMR840yaoJm1hGRI2N31Jzl+kMezBp/pvKO3QF4x9fLJVsv57gO3LqDt5GU=,iv:esxLD/mf4b3BjarAzBuJlQ8gqrQSeBE/yKiDOa/jqwE=,tag:M07RfCeo2sYuTGl1Bh3VDg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
