irc:
    server:
        oper:
            orcam:
                class: ENC[AES256_GCM,data:tTfDSykX+Pb47kba,iv:oRRx3xk8dKi4ycjb8nKhLMGNvzz6V8j/o17CJAj+R/Q=,tag:FnleqBeRaYgFgMJ98RPt5w==,type:str]
                whois-line: ENC[AES256_GCM,data:XE/UJ28EUhmrh+GQPOeLE9nZ7w==,iv:LBSGzn+CpvIpo4IS1H1e+jnIkBfGWRvH9UuZd7dV8JY=,tag:5Xwq124nnE7GNzZPT4Xp/g==,type:str]
                vhost: ENC[AES256_GCM,data:vRuz46bvdUsYRXziDRRqjSoxhZ4=,iv:lU9ZelP5ULDZiCH6MA+zsIplnqNLBJCneBcEiqzfmE4=,tag:1s2hH2kGppADpbH/Pozuyg==,type:str]
                hidden: ENC[AES256_GCM,data:5WUm1xI=,iv:8Mx+QhW9Qs6aSu7DO5fqo2rLIli38OH9xsAoHnqrwJ8=,tag:+FWpmml4+hsaiDamrxK2JQ==,type:bool]
                modes: ENC[AES256_GCM,data:jadsYo1Jt6m6Nuo317JvjQ==,iv:JtPvXegMu5Fcep70Com3I7M0JxUACXIu7IMfy732tpk=,tag:+9vVNhKx8kdpX/zpbMDDzw==,type:str]
                password: ENC[AES256_GCM,data:baeJ9k80yrCTYvlc5XNp1T0QDvUHzvGrUt/bnQcphRUZJbSxp6u9eRnU/UxRdWPbvGFDQ4/DwHJfv/cc,iv:M6M+k0BakPwh8jRPOo3C49L3bvjCco0ZkeLrHDiJZOg=,tag:eJhIeg9f/+mKZcJjhFoM6Q==,type:str]
            Striek:
                class: ENC[AES256_GCM,data:6rAF/nD4Q40Ytx5x,iv:3IKUPiZWd5clkLL8nwg/l445enUK8Vqso9lnVaL0KXs=,tag:3WbCjqtlaREexbuXenBoOQ==,type:str]
                whois-line: ENC[AES256_GCM,data:CTib0zpe+hU4XVfWTQN7w7lrEB2j11noRnfFQG7Lh8n2/bJfptsTlZ5TAg==,iv:gREUwvawGT0cFyrbsD+PCTg8FDOkoJSkqI4Cfhw4mA4=,tag:yBSrjgd+aqh5XmS1XyXKcA==,type:str]
                vhost: ENC[AES256_GCM,data:yh3DmKLFbPrL3T2r52oc+bwAPg==,iv:4TZYMXe4HEhi51PfV/o9tulmN3nh9mpsSQ6BrHnwGYM=,tag:NtyLHLiW9LksxNpdhDJYxA==,type:str]
                hidden: ENC[AES256_GCM,data:uG8FVEM=,iv:vp0MtP0SqQuHc0CJhXLvSJ4QbN9/ZvFt4+DI+rFVpDE=,tag:Xothjpiczr/3sOP7vzlYYQ==,type:bool]
                modes: ENC[AES256_GCM,data:WAqmQXFEZAvpEjwiSqIyJw==,iv:JA6TRVOiF6/bcP3yRHBMSd9CA6MUy+VuA8LQPMfyArM=,tag:5vHsr9pts4pVC0itmMlEYg==,type:str]
                password: ENC[AES256_GCM,data:0jivD1E6PjaW3XghWY0Jteyl6xyhH15ldRJGTtioBNt9KKoYdJL1CM55oWk4zaMzf2ctKjGOK57qKJh2,iv:kuGYz3Bd9Imxoyaw4uOLLlHhTJWucgCM38PrT0htzWY=,tag:LSBEiCFoxuRHAtiQ5GduIA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a7dumefn2xmd2rqenrldhlqzqedpepnp90e94trzu7eh6xp4hu4qzmv8cq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoelp6bFFhZ3dqSEdlb1JK
            d3BqeUpldkdCZ2QrY1hNSmZCc08zRHFtM0hJCmI0WGlkcEIyTlRMZm9CYXpoQ1lv
            T2dDaCswUHdSVmZvckcxWHkycE5wT0kKLS0tIGNIT0VORzVFWGxqQUdIZ0hpaUdp
            cjB4d05uRmVaQVhqM3ppajhjcVN1dUkKMbYZYqvAGQePXIFe1Qki3ioFQmHFztTp
            h1L/QQzny7y2K4W2mdsiW/nhRoZ8SZ0zNuGEsoaIlBnQ+M9GqRbFMg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zn9hyvar0dv75pvd9e4qkj549ltt3n0t9vwgkptrm0etphrhl3vshp6rd9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMT1c5anUwVkxhSHlJeGRW
            cDZpcEtzaGYzUzVnRGk5cXM5Tk85aXhnQ1hNCjFaL21EN2hIVTNqalYvZWN2ZUFY
            QmVjUm5COTZZKzNMZE9oeTNPTDlEbU0KLS0tIGNxWUtnaktyNHNwQVAxRHgwV2dm
            dWkwdC9ZMnowN2NhdGg5dzl5cmQwR1UKmD6k/vLE6b8z1+/4vOOdaM8hePh8xqbT
            cPbsnADRWQcHvQNPlI1VHxNx581Y/HjCydO4yHHypeWvnipwDGSacA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-10-11T01:50:59Z"
    mac: ENC[AES256_GCM,data:vcpQwkTNJTLY9IL+Y/r1DIlbyno7GXjq+B/SiXuTJXzLX/MsJfw+hkZ3AW5jcOeNPSgTuzFM/8HdLqub0y3dbiUYUqwfYt1vzWNrXY/12Pb9oyX/HjtGtDgftZt/9AkBzc5uKQVB5NP+/uUVjCNnfdNN8oHwET4XSwt5X6lhx58=,iv:XxlQHoaJiGl3hJATyt+hZv1hCNupyjYfrboBZ6j4dhs=,tag:9maUPfFCE8yKA3hAZRsP0A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
