nameOverride: ""
fullnameOverride: ""

irc:
  replicaCount: 1
  image:
    repository: ghcr.io/ergochat/ergo
    tag: v2.13.1
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
  imagePullSecrets: []
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  service:
    annotations: {}
    port: 6667
    tlsPort: 6697
  ingress:
    enabled: true
    annotations:
      external-dns.alpha.kubernetes.io/target: lb-trfk.unerror.network
      external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/router.tls.options: default
      traefik.ingress.kubernetes.io/service.serverstransport: default-chatbox-transport@kubernetescrd
    ingressClassName: networking-traefik
    hosts:
      - irc.unerror.com
      - irc.unerror.network
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  pvc:
    size: 1Gi
    accessModes:
      - ReadWriteMany
    storageClass: s3-default
  server:
    tls:
      enabled: true
      hostnames:
        - irc.unerror.com
        - irc.unerror.network
        - matrix.unerror.network
        - matrix.unerror.com
      issuerRef:
        name: letsencrypt-prod
        kind: ClusterIssuer
        group: cert-manager.io

tls:
  enabled: true
  hostnames:
    - irc.unerror.com
    - irc.unerror.network
    - matrix.unerror.network
    - unerror.network
    - matrix.unerror.com
    - synapse.unerror.com
    - unerror.com
    - www.unerror.com
    - element.unerror.com
    - element.unerror.network
    - chat.unerror.com
    - chat.unerror.network
    - chatbox-matrix-meetings-widget.unerror.com
    - matrix-meetings-bot.unerror.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io

sliding-sync-proxy:
  matrixServer: "https://matrix.unerror.com"
  postgresql:
    enabled: false
  externalPostgresql:
    # externalPostgresql is defined as extraEnv in secrets
    host: fake
    password: fake
  ingress:
    enabled: true
    serveSimpleClient: false
    className: networking-traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/router.tls.options: default
    hosts:
      - matrix-x.unerror.com
    tls:
      - secretName: sliding-sync-proxy-tls
        hosts:
          - matrix-x.unerror.com

matrix-synapse:
  serverName: unerror.com
  publicServerName: matrix.unerror.com
  config:
    turnUris: ["turn:turn.unerror.network?transport=tcp"]
    enableRegistration: false
    reportStats: false
  signingkey:
    job:
      enabled: false
    existingSecret: chatbox-matrix-signkey
    existingSecretKey: signing.key
  postgresql:
    enabled: false
  externalPostgresql:
    port: 25061
    username: matrix
    database: homeserver_synapse
    sslmode: require
    host: private-db-tor1-do-user-133480-0.b.db.ondigitalocean.com
    extraArgs:
      cp_max: 10
      cp_min: 5
  redis:
    master:
      podAnnotations:
        ad.datadoghq.com/redis.checks: |
          {
            "redisdb": {
              "init_config": {},
              "instances": [
                {
                  "host": "%%host%%",
                  "port":"6379",
                  "password":"%%env_REDIS_PASSWORD%%"
                }
              ]
            }
          }
    enabled: true
  volumePermissions:
    enabled: false
  persistence:
    enabled: true
    storageClass: s3-default
    accessMode: ReadWriteMany
    size: 20Gi
  ingress:
    traefikPaths: true
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/router.tls.options: default
    className: networking-traefik
    tls:
      - hosts:
          - matrix.unerror.com
          - synapse.unerror.com
        secretName: chatbox-crt-secret
    hosts:
      - matrix.unerror.com
      - synapse.unerror.com
    csHosts:
      - matrix.unerror.com
      - synapse.unerror.com
    wkHosts:
      - unerror.com
      - www.unerror.com
    paths:
      - path: /_matrix/media
        pathType: Prefix
        backend:
          service:
            name: matrix-media-repo
            port:
              number: 8000
    csPaths:
      - path: /_matrix/media
        pathType: Prefix
        backend:
          service:
          name: matrix-media-repo
          port:
            number: 8000
  wellknown:
    enabled: true
    server:
      m.server: "matrix.unerror.com:443"
    client:
      m.homeserver:
        base_url: "https://matrix.unerror.com"
      org.matrix.msc3575.proxy:
        url: "https://matrix-x.unerror.com"
  extraConfig:
    oidc_providers:
      - idp_id: "oidc"
        idp_name: "Unerror Auth"
        issuer: "https://auth.unerror.network/"
        client_id: "569033edde20009501ab"
        client_secret: "f87809d9060c00cf995e888e5966f611d4ee2fcf"
        scopes: ["openid", "profile"]
        allow_existing_users: true
        user_mapping_provider:
          config:
            localpart_template: "{{ user.preferred_username }}"
            confirm_localpart: true
    app_service_config_files:
      - /appservice-irc-registration.yaml
    max_upload_size: 128M
    max_image_pixels: 32M
    allow_guest_access: false
    auto_join_rooms:
      - "#offtopic:unerror.com"
    trusted_third_party_id_servers: [matrix.unerror.com]
    email:
      app_name: Unerror Network Matrix
      client_base_url: https://matrix.unerror.com
      enable_notifs: true
      notif_for_new_users: true
      notif_from: Unerror Network Matrix <chatbox@unerror.com>
      require_transport_security: true
      smtp_host: smtp.sendgrid.net
      smtp_port: 587
      enable_tls: true
    url_preview_enabled: true
    url_preview_ip_range_blacklist:
      - "127.0.0.0/8"
      - "10.0.0.0/8"
      - "172.16.0.0/12"
      - "192.168.0.0/16"
      - "100.64.0.0/10"
      - "192.0.0.0/24"
      - "169.254.0.0/16"
      - "192.88.99.0/24"
      - "198.18.0.0/15"
      - "192.0.2.0/24"
      - "198.51.100.0/24"
      - "203.0.113.0/24"
      - "224.0.0.0/4"
      - "::1/128"
      - "fe80::/10"
      - "fc00::/7"
      - "2001:db8::/32"
      - "ff00::/8"
      - "fec0::/10"
  synapse:
    extraVolumes:
      - name: appservice-irc-registration
        secret:
          secretName: chatbox-matrix-appservice-irc
    extraVolumeMounts:
      - name: appservice-irc-registration
        mountPath: /appservice-irc-registration.yaml
        subPath: appservice-registration-irc.yaml
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/path: /_synapse/metrics
      prometheus.io/port: "9090"
    extraEnv:
      - name: LD_PRELOAD
        value: /usr/lib/x86_64-linux-gnu/libjemalloc.so.2
      - name: SYNAPSE_CACHE_FACTOR
        value: "2"
  workers:
    default:
      volumes:
        - name: appservice-irc-registration
          secret:
            secretName: chatbox-matrix-appservice-irc
      volumeMounts:
        - name: appservice-irc-registration
          mountPath: /appservice-irc-registration.yaml
          subPath: appservice-registration-irc.yaml
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /_synapse/metrics
        prometheus.io/port: "9090"
      extraEnv:
        - name: LD_PRELOAD
          value: /usr/lib/x86_64-linux-gnu/libjemalloc.so.2
        - name: SYNAPSE_CACHE_FACTOR
          value: "2"
    generic_worker:
      enabled: true
      replicaCount: 2
      csPaths:
        ## Sync requests
        - "/_matrix/client/(r0|v3)/sync$"
        - "/_matrix/client/(api/v1|r0|v3)/events$"
        - "/_matrix/client/(api/v1|r0|v3)/initialSync$"
        - "/_matrix/client/(api/v1|r0|v3)/rooms/[^/]+/initialSync$"

        ## Client API requests
        - "/_matrix/client/(api/v1|r0|v3|unstable)/createRoom$"
        - "/_matrix/client/(api/v1|r0|v3|unstable)/publicRooms$"
        - "/_matrix/client/(api/v1|r0|v3|unstable)/rooms/.*/joined_members$"
        - "/_matrix/client/(api/v1|r0|v3|unstable)/rooms/.*/context/"
        - "/_matrix/client/(api/v1|r0|v3|unstable)/rooms/.*/members$"
        - "/_matrix/client/(api/v1|r0|v3|unstable)/rooms/.*/state$"
        - "/_matrix/client/v1/rooms/.*/hierarchy$"
        - "/_matrix/client/unstable/org.matrix.msc2716/rooms/.*/batch_send$"
        - "/_matrix/client/unstable/im.nheko.summary/rooms/.*/summary$"
        - "/_matrix/client/(r0|v3|unstable)/account/3pid$"
        - "/_matrix/client/(r0|v3|unstable)/account/whoami$"
        - "/_matrix/client/(r0|v3|unstable)/devices$"
        - "/_matrix/client/versions$"
        - "/_matrix/client/(api/v1|r0|v3|unstable)/voip/turnServer$"
        - "/_matrix/client/(api/v1|r0|v3|unstable)/rooms/.*/event/"
        - "/_matrix/client/(api/v1|r0|v3|unstable)/joined_rooms$"
        - "/_matrix/client/(api/v1|r0|v3|unstable)/search$"

        ## Encryption requests
        - "/_matrix/client/(r0|v3|unstable)/keys/query$"
        - "/_matrix/client/(r0|v3|unstable)/keys/changes$"
        - "/_matrix/client/(r0|v3|unstable)/keys/claim$"
        - "/_matrix/client/(r0|v3|unstable)/room_keys/"

        ## Registration/login requests
        - "/_matrix/client/(api/v1|r0|v3|unstable)/login$"
        - "/_matrix/client/(r0|v3|unstable)/register$"
        - "/_matrix/client/v1/register/m.login.registration_token/validity$"

        ## Event sending requests
        - "/_matrix/client/(api/v1|r0|v3|unstable)/rooms/.*/redact"
        - "/_matrix/client/(api/v1|r0|v3|unstable)/rooms/.*/send"
        - "/_matrix/client/(api/v1|r0|v3|unstable)/rooms/.*/state/"
        - "/_matrix/client/(api/v1|r0|v3|unstable)/rooms/.*/(join|invite|leave|ban|unban|kick)$"
        - "/_matrix/client/(api/v1|r0|v3|unstable)/join/"
        - "/_matrix/client/(api/v1|r0|v3|unstable)/profile/"

        ## User directory search requests
        - "/_matrix/client/(r0|v3|unstable)/user_directory/search"

        ## Worker event streams
        ## See https://matrix-org.github.io/synapse/latest/workers.html#stream-writers
        ##

        ## The typing event stream
        # - "/_matrix/client/(api/v1|r0|v3|unstable)/rooms/.*/typing"

        ## The to_device event stream
        - "/_matrix/client/(r0|v3|unstable)/sendToDevice/"

        ## The account_data event stream
        # - "/_matrix/client/(r0|v3|unstable)/.*/tags"
        # - "/_matrix/client/(r0|v3|unstable)/.*/account_data"

        ## The receipts event stream
        # - "/_matrix/client/(r0|v3|unstable)/rooms/.*/receipt"
        # - "/_matrix/client/(r0|v3|unstable)/rooms/.*/read_markers"

        ## The presence event stream
        - "/_matrix/client/(api/v1|r0|v3|unstable)/presence/"

      paths:
        ## Federation requests
        - "/_matrix/federation/v1/event/"
        - "/_matrix/federation/v1/state/"
        - "/_matrix/federation/v1/state_ids/"
        - "/_matrix/federation/v1/backfill/"
        - "/_matrix/federation/v1/get_missing_events/"
        - "/_matrix/federation/v1/publicRooms"
        - "/_matrix/federation/v1/query/"
        - "/_matrix/key/v2/server"
        - "/_matrix/federation/v1/make_join/"
        - "/_matrix/federation/v1/make_leave/"
        - "/_matrix/federation/(v1|v2)/send_join/"
        - "/_matrix/federation/(v1|v2)/send_leave/"
        - "/_matrix/federation/(v1|v2)/invite/"
        - "/_matrix/federation/v1/event_auth/"
        - "/_matrix/federation/v1/exchange_third_party_invite/"
        - "/_matrix/federation/v1/user/devices/"
        - "/_matrix/key/v2/query"
        - "/_matrix/federation/v1/hierarchy/"

        ## Inbound federation transaction request
        - "/_matrix/federation/v1/send/"
        ## Health check
        - "/health"
    pusher:
      enabled: true
    federation_sender:
      enabled: true
    media_repository:
      enabled: true
      csPaths:
        - "/_matrix/media/.*"
        - "/_synapse/admin/v1/purge_media_cache$"
        - "/_synapse/admin/v1/room/.*/media"
        - "/_synapse/admin/v1/user/.*/media"
        - "/_synapse/admin/v1/media/"
        - "/_synapse/admin/v1/quarantine_media/"
        - "/_synapse/admin/v1/users/.*/media$"
      paths:
        - "/_matrix/media/.*"
    frontend_proxy:
      enabled: true
      listeners: [client]
      csPaths:
        - "/_matrix/client/(api/v1|r0|v3|unstable)/keys/upload"
    synchrotron:
      enabled: true
    user_dir:
      enabled: true

element-web:
  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/router.tls.options: default
    hosts:
      - unerror.network
      - matrix.unerror.network
      - matrix.unerror.com
      - element.unerror.com
      - element.unerror.network
      - chat.unerror.com
      - chat.unerror.network
    tls:
      - secretName: chatbox-crt-secret
  defaultServer:
    url: https://matrix.unerror.com
    name: Unerror Network Matrix
  nginxConfig: |-
    add_header X-Frame-Options SAMEORIGIN;
    add_header X-Content-Type-Options nosniff;
    add_header X-XSS-Protection "1; mode=block";
    add_header Content-Security-Policy "frame-ancestors 'self'";
  config:
    disable_custom_urls: false
    disable_guests: false
    disable_login_language_selector: false
    disable_3pid_login: false
    brand: element
    default_server_config:
      m.homeserver:
        base_url: "https://matrix.unerror.network"
        server_name": "matrix.org"
    bug_report_endpoint_url: https://element.io/bugreports/submit
    defaultCountryCode: US
    showLabsSettings: true
    features:
      feature_pinning: labs
      feature_custom_status: labs
      feature_custom_tags: labs
      feature_state_counters: labs
    default_federate: true
    default_theme: dark
    roomDirectory:
      servers:
        - unerror.com
    welcomeUserId: "@element-bot:unerror.com"
    piwik:
      url: https://unerror.com/
      whitelistedHSUrls:
        - https://matrix.unerror.network
      whitelistedISUrls:
        - https://matrix.unerror.com
      siteId: 1
    enable_presence_by_hs_url:
      https://matrix.unerror.com: true
    settingDefaults:
      breadcrumbs: true

matrix-appservice-irc:
  volumes:
    - name: ssl
      secret:
        secretName: postgres-ca-cert
  volumeMounts:
    - name: ssl
      mountPath: /ssl/db-ca.crt
      subPath: db-ca.crt
  env:
    - name: NODE_EXTRA_CA_CERTS
      value: /ssl/db-ca.crt
    - name: NODE_TLS_REJECT_UNAUTHORIZED
      value: "0"
  registration:
    id: appservice-irc
    de.sorunome.msc2409.push_ephemeral: true
    protocols:
      - irc
    namespaces:
      rooms:
        - exclusive: false
          regex: "!CndlWZukCBAXQKSTgg:unerror.com"
        - exclusive: false
          regex: "!MgMAsxJzkeiUxYwyNS:unerror.com"
        - exclusive: false
          regex: "!THQzArbJSBoThbyySC:unerror.com"
      users:
        - exclusive: true
          regex: '@irc_.*:unerror\.com'
    rate_limited: false
    sender_localpart: irc_bot
    url: http://chatbox-matrix-appservice-irc:8090
  config:
    homeserver:
      domain: unerror.com
      enablePresence: true
      media_url: https://matrix.unerror.com
      url: https://matrix.unerror.com
    ircService:
      ident:
        enabled: true
      provisioning:
        enabled: true
        widget: true
      bridgeInfoState:
        enabled: true
        initial: true
      servers:
        chatbox-ircd:
          sslselfsign: true
          allowExpiredCerts: false
          botConfig:
            enabled: true
            joinChannelsIfNoUsers: true
            nick: MatrixBot[un]
          ircClients:
            allowNickChanges: true
            concurrentReconnectLimit: 50
            idleTimeout: 10800
            lineLimit: 3
            maxClients: 30
            nickTemplate: $DISPLAY[m]
            reconnectIntervalMs: 5000
          mappings:
            "#krokbot":
              roomIds:
                - "!THQzArbJSBoThbyySC:unerror.com"
            "#lounge":
              key: r@ns0n
              roomIds:
                - "!MgMAsxJzkeiUxYwyNS:unerror.com"
            "#offtopic":
              roomIds:
                - "!CndlWZukCBAXQKSTgg:unerror.com"
          matrixClients:
            displayName: $NICK
            joinAttempts: -1
            userTemplate: "@irc_$NICK"
          membershipLists:
            channels:
              - channel: "#lounge"
                ircToMatrix:
                  incremental: true
                  initial: true
              - channel: "#krokbot"
                ircToMatrix:
                  incremental: true
                  initial: true
              - channel: "#offtopic"
                ircToMatrix:
                  incremental: true
                  initial: true
            enabled: true
            floodDelayMs: 10000
            global:
              ircToMatrix:
                incremental: true
                initial: true
              matrixToIrc:
                incremental: true
                initial: true
            rooms:
              - matrixToIrc:
                  incremental: true
                  initial: true
                room: "!MgMAsxJzkeiUxYwyNS:unerror.com"
              - matrixToIrc:
                  incremental: true
                  initial: true
                room: "!THQzArbJSBoThbyySC:unerror.com"
              - matrixToIrc:
                  incremental: true
                  initial: true
                room: "!CndlWZukCBAXQKSTgg:unerror.com"
          modePowerMap:
            a: 100
            o: 50
            v: 1
          name: Unerror IRC
          port: 6668
          privateMessages:
            enabled: true
            federate: true
          sasl: true
          sendConnectionMessages: true
    database:
      engine: "postgres"

matrix-meetings-widget:
  image:
    repository: ghcr.io/nordeck/matrix-meetings-widget
    pullPolicy: IfNotPresent
    tag: 1.6.1
  ingress:
    enabled: true
    className: networking-traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/router.tls.options: default
  settings:
    hostname: unerror.com

matrix-meetings-bot:
  image:
    repository: ghcr.io/nordeck/matrix-meetings-bot
    pullPolicy: IfNotPresent
    tag: 2.8.0
  ingress:
    enabled: true
    className: networking-traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/router.tls.options: default
    hosts:
      - host: matrix-meetings-bot.unerror.com
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: chatbox-crt-secret

  settings:
    widgetUrl: https://chatbox-matrix-meetings-widget.unerror.com
    config: {}
  # Controls for the state that is shared with users who receive an invite
  # to a room
  room_prejoin_state:
    additional_event_types:
      - m.space.parent
      - net.nordeck.meetings.metadata
      - m.room.power_levels
