nameOverride: ""
fullnameOverride: ""

irc:
  replicaCount: 1

  image:
    repository: ergochat/ergo
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"

  imagePullSecrets: []

  podAnnotations: {}

  podSecurityContext: {}

  securityContext: {}

  service:
    externalName:
      name: lb.unerror.network
      annotations:
        external-dns.alpha.kubernetes.io/hostname: irc.unerror.com
        external-dns.alpha.kubernetes.io/target: lb.unerror.network
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
    annotations: {}
    port: 6667
    tlsPort: 6697

  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
      nginx.ingress.kubernetes.io/secure-backends: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-ssl-secret: default/chatbox-crt-secret
      nginx.ingress.kubernetes.io/proxy-ssl-verify: "true"
      external-dns.alpha.kubernetes.io/target: lb.unerror.network
      external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"

    ingressClassName: nginx
    hosts:
      - irc.unerror.com
      - irc.unerror.network

  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

  pvc:
    size: 1Gi
    accessModes:
      - ReadWriteOnce
  newpvc:
    size: 1Gi
    accessModes:
      - ReadWriteMany
    storageClass: csi-s3

  server:
    tls:
      dns01: "true"
      enabled: true
      hostnames:
        - irc.unerror.com
        - irc.unerror.network
      issuerRef:
        name: letsencrypt-prod
        kind: ClusterIssuer
        group: cert-manager.io
matrix-synapse:
  serverName: unerror.network
  publicServerName: matrix.unerror.network
  image:
    tag: v1.44.0
  config:
    turnUris: [] # xx: add when turn
    turnSecret: ""
  enableRegistration: true
  synapse:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/path: /_synapse/metrics
      prometheus.io/port: 9090
  extraEnv:
    - name: LD_PRELOAD
      value: /usr/lib/x86_64-linux-gnu/libjemalloc.so.2
    - name: SYNAPSE_CACHE_FACTOR
      value: "2"
ma1sd:
  image:
    tag: 2.5.0
  serviceAccount:
    create: false
  persistence:
    enabled: false
  ingress:
    enabled: true
    hosts:
      - host: matrix.unerror.network
    tls:
      - hosts:
          - matrix.unerror.network
  config:
    dns:
      overwrite:
        homeserver:
          client:
            - name: matrix.unerror.network
              value: "http://chatbox-synapse-matrix-synapse:8008"
    hashing:
      algorithms:
        - none
        - sha256
      delay: 2m
      enabled: true
      hashStorageType: sql
      pepperLength: 20
      requests: 10
      rotationPolicy: per_requests
    key:
      path: /etc/ma1sd/signing.key
    matrix:
      domain: unerror.unerror.network
      v1: true
      v2: true
    server:
      name: matrix.unerror.network
    storage:
      backend: postgresql
    synapseSql:
      enabled: true
      type: postgresql
    notification:
      handler:
        email: "sendgrid"
      handlers:
        sendgrid:
          identity:
            from: chatbox@unerror.network
            name: Unerror Chatbox Matrix
    threepid:
      email:
        identity:
          from: chatbox@unerror.network
