# Default values for chatbox.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ergochat/ergo
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  externalName:
    name: lb.unerror.network
    annotations:
      external-dns.alpha.kubernetes.io/hostname: irc.unerror.network
      external-dns.alpha.kubernetes.io/target: lb.unerror.network
      external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
  annotations:
  port: 6667
  tlsPort: 6697

ingress:
  enabled: false
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          backend:
            serviceName: chart-example.local
            servicePort: 80

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

pvc:
  size: 1Gi
  accessModes:
    - ReadWriteOnce

server:
  tls:
    dns01: "true"
    enabled: true
    hostnames:
      - irc.unerror.network
    issuerRef:
      name: letsencrypt-prod
      kind: ClusterIssuer
      group: cert-manager.io
  config: |
    ssz
