bitcoind:
    config:
        rpcauth: ENC[AES256_GCM,data:if2kYa5gx0zEVr9d/9bRtBcZBH+KEZie+SyAXrauurkCECi2mPXELC8wIz+qqGHfMWicsxk/nyPfvzKdVB6Bz84OFfgdKP9AiXWy2XsW4b8BEKe/XXXwoE78NMJXQSjhwMRTKEvydg==,iv:TryXNnTKLoNKdYzjlmygTMzII6ftgA7ZIMsDKZTENOA=,tag:LkO8CauXfuJBcjEnFEfvkg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a7dumefn2xmd2rqenrldhlqzqedpepnp90e94trzu7eh6xp4hu4qzmv8cq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOV2hWaEl4TGhhWVZVcFl4
            RUNiYXVYOVYxZmVtVkhFbmRuTzcyRlcrMUVnCkR6VjZVazNadmNiNEc4VU14UFJT
            NnVwSmk1Zmh6cDk5WllZMlpYVHpkYXMKLS0tIGVuTDIxU0x3Tlk5dVRxWWJ0Q1ZH
            UmFkVG84THU3L1JMUExyRm9adVFPVXMKxLqaPOTnDqszRFYZBQR+YQxhwA1C8kd7
            pAHfFOwwjIIc7lZOrBBNUANRVYRzWNtrFZuyNLGsYemcarumC2Az0Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zn9hyvar0dv75pvd9e4qkj549ltt3n0t9vwgkptrm0etphrhl3vshp6rd9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVYnZzV3R3UUJYTXE4NXZ2
            MTM0bmQwUFdVemo4UExBdTB0STVjMDc3MUIwCllTdkxSd0JXVlpmdnJSQXFoUEhL
            d2NudDhnTlJLbHdRVEhRektvZ0RwOUUKLS0tIEJnclRNMzVhc0lqNm5NdHZaS1lV
            RGVlditXcWNYY0VUODlOUnhtTVlGSHMKCqF62mBxa0bmyK3DKooIOLlUz+L2l5gU
            lPru9S/Vw4ve3Z5yNM1I6QkDyK5SgW62T08eh7uIOneIZR5a7IPGCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-05T02:37:06Z"
    mac: ENC[AES256_GCM,data:t2MNN0oMMCghbnIQ8GLTveBJ/J7wZI2nbUQ79xFyq8ibDReAcYJDy9fZOl3LxX6hhcVO16l6ix9hk3dP6rJGwGdiM9LlNzcznTVlqB6gULWxx212bgqojOoo9i7kfF+IDi+3Hb6RcS3y4x569C7ho+WRhyO0rP6HjAygkpKIyZw=,iv:8uTtzqHmspB8wQFHHaRugvLxA1fgV/y6ow10II1bc4Y=,tag:JXNys2vfnmuFsi0le19H0A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
