bitcoind:
  config:
    persistence:
      enabled: true
      size: 500Gi
      storageClassName: s3-default

    p2p:
      enabled: true
      addr: 0.0.0.0
      port: 8333
    rpc:
      enabled: true
      addr: 0.0.0.0
      port: 8332
    zmqblock:
      enabled: true
      addr: 0.0.0.0
      port: 28332
    zmqtx:
      enabled: true
      addr: 0.0.0.0
      port: 28333
