gha-runner-scale-set-controller:
  serviceAccount:
    create: true
    name: gha-runner-controller-sa
gha-runner-scale-set:
  githubConfigUrl: "https://github.com/unerror"
  maxRunners: 5
  minRunners: 0
  controllerServiceAccount:
    namespace: default
    name: gha-runner-controller-sa
gha-runner-scale-set-dwn-rs:
  githubConfigUrl: "https://github.com/enmand/dwn-rs"
  maxRunners: 5
  minRunners: 0
  runnerScaleSetName: "dwn-rs"
  controllerServiceAccount:
    namespace: default
    name: gha-runner-controller-sa
  template:
    spec:
      containers:
        - name: runner
          image: "ghcr.io/quipper/actions-runner/cache:main-ubuntu20"
          imagePullPolicy: Always
          command: ["/home/runner/run.sh"]
