actions-runner-controller:
  replicaCount: 1
  authSecret:
    create: true
  metrics:
    serviceMonitor: true
  githubWebhookServer:
    enabled: true
    secret:
      enabled: true
      create: true
    ingress:
      enabled: true
      ingressClassName: networking-traefik
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
        traefik.ingress.kubernetes.io/router.tls.options: default
      hosts:
        - host: action-ci-runners.unerror.network
          paths:
            - path: /*
              pathType: ImplementationSpecific

      tls:
        - hosts:
            - action-ci-runners.unerror.network
          secretName: action-ci-runners-tls
          issuerRef:
            name: letsencrypt-prod
            kind: ClusterIssuer
