apiVersion: v1
kind: Secret
metadata:
  name: kubepromsecret
type: Opaque
data:
  # You can include additional key value pairs as you do with Opaque Secrets
  username: {{ .Values.grafana_username | b64enc}}
  password: {{ .Values.grafana_password | b64enc}}
