apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: ns-record
spec:
	providerSpecific:
		- name: cloudflare-proxied
		- value: "false"
  endpoints:
  - dnsName: turn.unerror.network
    recordTTL: 300
    recordType: CNAME
    targets:
    - lb-trfk.unerror.network
