apiVersion: v1
kind: Secret
metadata:
  name: {{ include "networking.fullname" . }}-tailscale-auth-relay
stringData:
  AUTH_KEY: {{ .Values.tailscale.relay.authKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "networking.fullname" . }}-tailscale-auth-traefik
stringData:
  AUTH_KEY: {{ .Values.tailscale.traefik.authKey }}