apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.tailscale.serviceAccount }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tailscale
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create"]
  - apiGroups: [""]
    resourceNames: ["{{ .Values.tailscale.state }}"]
    resources: ["secrets"]
    verbs: ["get", "update"]
  {{- range $val := .Values.tailscale.additionalStates }}
  - apiGroups: [""]
    resourceNames: ["{{ $val }}"]
    resources: ["secrets"]
    verbs: ["get", "update"]
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tailscale
subjects:
- kind: ServiceAccount
  name: {{ .Values.tailscale.serviceAccount }}
roleRef:
  kind: Role
  name: tailscale
  apiGroup: rbac.authorization.k8s.io
{{- range $val := .Values.tailscale.additionalserviceAccountBindings }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tailscale-{{ . }}
subjects:
- kind: ServiceAccount
  name: {{ . }}
roleRef:
  kind: Role
  name: tailscale
  apiGroup: rbac.authorization.k8s.io
{{- end }}