apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "networking.fullname" . }}-metrics
  labels:
    {{- include "networking.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: traefik
  podMetricsEndpoints:
    - port:  metrics
      path: /metrics
  namespaceSelector:
    matchNames:
    - une-sys
