{{- if .Values.traefik.dashboard.tls.enabled -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "networking.fullname" . }}-traefik-internal-cert
spec:
  secretName: {{ .Values.traefik.dashboard.tls.secretName }}
	{{- with .Values.traefik.dashboard.hosts }}
  dnsNames:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.traefik.dashboard.tls.issuerRef }}
  issuerRef:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ template "networking.fullname" . }}-traefik-dashboard-internal
  annotations:
    helm.sh/hook: "post-install,post-upgrade"
    app.kubernetes.io/name: {{ include "networking.fullname" . }}
    app.kubernetes.io/app: traefikk
    app.kubernetes.io/instance: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ template "networking.fullname" . }}
    helm.sh/chart: {{ template "networking.fullname" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  entryPoints:
    - websecure-tsnet
  routes:
  {{- range .Values.traefik.dashboard.hosts }}
  - match: Host(`{{ . }}`)
    kind: Rule
    services:
    - name: api@internal
      kind: TraefikService
  {{- end }}
  {{- if .Values.traefik.dashboard.tls.enabled }}
  tls:
    secretName: {{ .Values.traefik.dashboard.tls.secretName }}
  {{- end }}
