vaultwarden:
    env:
        DATABASE_URL: ENC[AES256_GCM,data:Kn0/TYrkDmCsFj8WDlWCLf17uIUJTYdt7AonX1itNQlDPU1tK3K6PKk8TJj5kSkBTbR9W/084FvA1v9/7Dz6BIsRspIeRWrxJK/aOA6Vy8kCjTLjAYBzsblikCjOwUQ3vj+c+z5IfnpNXNsba5qc8p9dN+Q0gu5L6S42D/DJFkhjdk26/0NFpTwrvfE=,iv:nVTBHWHbukmV0bGpI/Qh/5cBgl1wYqHaUaewyEWS6nE=,tag:t6a2dlx/f1EFpLZM5EG1tw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a7dumefn2xmd2rqenrldhlqzqedpepnp90e94trzu7eh6xp4hu4qzmv8cq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKcGNuMDNJMFBDQXBnMU5F
            TXAxcEg4a1FkR0Z3ZlBhUXhwSGVoZFhaalNVCklZdkYwWDNORWxNckt6bUNVSllj
            ZmI2cUE0c3AxbmlHaURYaGRtYlhsY28KLS0tIFpGaUo3d2JIaW9EK1paT2JYT0Nv
            VlFxTy8xUVNucjQ0WWRDWm44azZBc0kKUFMwpxU/vnv/KFc4ClGLSru+8V8mTTjD
            JMDIJcpMXKnWFVYKVYaMElmKXoLAyChTbXMn7o2AN574cth7w81J7w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zn9hyvar0dv75pvd9e4qkj549ltt3n0t9vwgkptrm0etphrhl3vshp6rd9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPaUxTMkZlMVdGeUlHbUpj
            TUhaeTFXNWNiT3dVWnI1OGdDREZiMzVOdDFRClk2L0xpWDZMVzFaMmhGdjUrUVAr
            QjMzNGxjdzh5K1gyT2NONUw5bWNUZXcKLS0tIEI1anVraitTYUx2ZDBhNzY4KzNa
            UThNMVQrZ09uY053ZFlvRURvV3NCV0EKrdM1Yrb7K0+8gMESFx6e2JhAJnmP7kLi
            RjC8j2aACWGs4xNo6H2O65/8KmOIx/lgmfXZDUhLT3cSZWR402y4cQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-06T03:10:36Z"
    mac: ENC[AES256_GCM,data:8/EyQ3/z6Is6zf019pJgpX9XJkDoublH+p15pQDzl52fuQAajhTax2CMtkk+VOK1dBcn+W+q0st71LI3hAqfkU1BmvJ76ooGYj8avN0tZ1ch50/CqMcxETMMa0DpwFjY9sPF4zGkw510hD4Blr78n26O/5K23YAu4gxR9k0yF1Q=,iv:CTp090Qh0/xIFjaiwmmPdCvPN6KcEfoLHBdVamQk9Ws=,tag:Bv5g3PSrw2tB+0JDlfusoQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
