vaultwarden:
  image:
    # -- image repository
    repository: vaultwarden/server
    # -- image pull policy
    pullPolicy: IfNotPresent
    # -- image tag
    # @default -- chart.appVersion
    tag:

  strategy:
    type: Recreate

  env:
    # -- Config dir
    DATA_FOLDER: "config"

  service:
    main:
      ports:
        http:
          port: 80
        websocket:
          enabled: true
          port: 3012

  ingress:
    main:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      enabled: true
      tls:
        - hosts:
            - warden.unerror.network
          secretName: vaultwarden-ingress-tls
      hosts:
        - host: warden.unerror.network
          paths:
            - path: /
              pathType: Prefix
              service:
                port: 80
            - path: /notifications/hub/negotiate
              pathType: Prefix
              service:
                port: 80
            - path: /notifications/hub
              pathType: Prefix
              service:
                port: 3012

  persistence:
    ssl:
      enabled: true
      type: secret
      name: postgres-ca-cert
    config:
      enabled: true
  mariadb:
    enabled: false
  postgresql:
    enabled: false
