argo-cd:
    server:
        config:
            dex\.config: ENC[AES256_GCM,data:kGa+R3LA++ySWazpVMowrAOMfxYRVjZ/tbKBAlT2QKKnRwX0HKllgh+Da+D58OxCJ+Agw8Y96G7tAEg9f/zXpi4Kc7DhKfIzW0WZ7xll3jkRHlbk+pbZRkQuzzBgxylaFQuoEZ7XhVyV95hIyfHmxxRF8OfkqoxY/KbFzsWhfdkg1JIZVLnqj+DBfCU6GPW7f8kJXYR6ItM/dX3faZCdW1pSHY5Lpmt51w1z4ITFk9h1NTeU/20aoNDff3bLBQwcH14lMtelPa48bt18XQbdsPttflGJVc6TOF0YbP8A5TXodk1FS6DeViOzSs8VAm0+0pRWns9r3kRi2zKn6VcQUgOMjTr12bQ8gUn0b86fV5RDL53ETbWz8npQK7kgp7/cI5rtA7F7f+ajaWY/,iv:azJoeF+H0hIgDBEdYOPV2c+jmn6mXC+dTkV9mwZUW44=,tag:chS7TJCN1sNquRA1rucoGQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a7dumefn2xmd2rqenrldhlqzqedpepnp90e94trzu7eh6xp4hu4qzmv8cq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBISmNLTkp0VVR4RmxabFhW
            aFlubzNndVRTSzYzbElMVGdqbG5oaWI1enhFCmtGdHNNblNhMjBJYjQzQXlIc3lM
            UTN3NThTLzlpZHFCaWxYOWZoNkp2WjQKLS0tIDNteExNNEFsMGFhKytxa0RtbUJ4
            NTIxWWZncFh2TjhTVFpvS3JUSGVEOHcKTQzKfQzoSbJNXvXCT6mD9fcRTgjvMv8x
            tui8VYaFJHJhrSDnkvMmReynm7qxVLmVENIeREuROT9LpFo7487LwA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zn9hyvar0dv75pvd9e4qkj549ltt3n0t9vwgkptrm0etphrhl3vshp6rd9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4WEVXdWc3OEhmYmdTYm9C
            V1VYU1RIQmQvSGI3T3p4VFZKNXY0dksvcEJjClRyMDdMTk1YR210ME1VWDhZaVNG
            WENyYzZVdmZuQ0FPazRha2NlS3VFSlkKLS0tIExDanRYNnhiRlczaTF5U1lBWmE5
            VUZlRUkrK2E3bnFiT2lwN1BKVHRtcG8KdL3D2Sr8SPUNdTN8zc7V56xGva5P8jwS
            5hA27YhOrp+Nme8unpODA6Ziak9UQh/ShAQaJN0dR25flybSZTM3VA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-10-02T02:01:43Z"
    mac: ENC[AES256_GCM,data:RWG+eKtu9Os50raqHlMjDChd+IY0rCUJJ5L/WagqWaN9fSXY4yxHZMEgNveTa5WQCuNnuV1qfdaGWEtYWK993ZSglh2qE8gu+IxxX1ub5filssBwDVpUp9tqsAVHXXkYeHEE+Vuz4glUuMW5Ur2arnrHUh2FZMCWXsYtCiHHKPE=,iv:5/QiEO825Yml6TaJQBMHw7bGWjfdgqSbvUKuYEjMwJk=,tag:SmUDeLDxaOoJFC2tLrmluQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
