argo-cd:
    configs:
        secret:
            githubSecret: ENC[AES256_GCM,data:8gK/tLGtIthXBAEfxsOJpFuHSZgANKdCN5S9zVHlyLh8uAFauoOa6EhHMY29ifqO3gL3xw/YLQkdAn66PZs6+BqtcysVRR20ap1Vc0/4v08i1Ra7ACVzOcovrpgCE8Y0VS3+KJZ/0SNAQ8wmovSeAX3Wnj/mlUzaLfVwJqCPsLmxFiODSJOL4mamLC+GPKggtGpBAMt6wSjO8thnMB7S1FKXumfsHzxsuC5wTNXL+42I2mxODopz/4LJ2mfkqTHvYpbMQFydwjZIbEVCRPgBWT9mbFgUIxFQSRrpQbgOgkX7slqBn7EfoUc/V5jv4TGFRiIiOOIG3A1IPFvMLhNZDQ==,iv:ZvLARS5lVt2PMM2MgzTUOxeLV7ikZSxXX0MF4D8GsJE=,tag:KBd3KD63KWBHn/c68EwnjA==,type:str]
    server:
        config:
            dex.config: ENC[AES256_GCM,data:/bSJzBrFFxLu7alj8UtmOOrtdmJzhhRx9ktFS0qf+ho+r3FsgkgQY2G/ImnztVoKQZCtzGcr2lTf3EInoi0lW7PYPkENWvCb7C34SN7vGhIWQdg2i3YwZiE4STH6RfA1SDn8jo5twOZd+7jgUaGwF5FRXHOfeUtJT2VVBBbeFeAjbIKDAdSHd78n0irjUMKvf5uJ758Yog31zJKxALHN5QawSEssADsKcfT93H/4sOo/BPPU3bsjs4ehNSTxSDJ+4qNLEvEW6cnkefyaZst6Dyvt3QTRQz//yjuBrqVh8smhr+FEZEYLQbxOoENuEh7nNb9TUzbFHzZqN3pRLplw3qDqq4pswbqvuok2cu5JG0EqVaz0JstqaXRDTiu1HIjvAo+o8ktsVHl59gJ+LucTmvS/gLGOyOlQ4CQWs6zdwXpGdpreL9ec2zr113tMZKeJBxmwo/mtAWMaWmUqsgidq2L5VAGNGfB5x4LbKySJ+z0W7B8UqEhqLurqu9t9hC/C60EAJVpG+uUcEVkjkwsRtxWudUy1y1U62Wmh/w4B0Z2HsSafTnWt4iYOw2C+k2XPhN8FKsWVoucRgydBa4Js2n461xCj1KmI7biDFx+D3fBbeLANWymwNY8erMV7/DiS4QZGP4ueQO68C5siuumBLFlaXGKPCcf+DaOnZPVew93yEg9w3OxsT0R/S0f1jT2MyapUq7p6GuNO4UuYr/wcyMZW/TR2GkuuAUFy4WoiYOyEpKeCKANkZz5H94YI7z9K/9uZMkNO6D5yvq6wQ8k0ydZ/zlRoCvIQgOY=,iv:IVGgO2JJz1deXYTOK+kfegvJgi4Gnfuf5dFPpJyVyoE=,tag:yldov5kWGaDOQl3JQoqNXA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a7dumefn2xmd2rqenrldhlqzqedpepnp90e94trzu7eh6xp4hu4qzmv8cq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBISmNLTkp0VVR4RmxabFhW
            aFlubzNndVRTSzYzbElMVGdqbG5oaWI1enhFCmtGdHNNblNhMjBJYjQzQXlIc3lM
            UTN3NThTLzlpZHFCaWxYOWZoNkp2WjQKLS0tIDNteExNNEFsMGFhKytxa0RtbUJ4
            NTIxWWZncFh2TjhTVFpvS3JUSGVEOHcKTQzKfQzoSbJNXvXCT6mD9fcRTgjvMv8x
            tui8VYaFJHJhrSDnkvMmReynm7qxVLmVENIeREuROT9LpFo7487LwA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zn9hyvar0dv75pvd9e4qkj549ltt3n0t9vwgkptrm0etphrhl3vshp6rd9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4WEVXdWc3OEhmYmdTYm9C
            V1VYU1RIQmQvSGI3T3p4VFZKNXY0dksvcEJjClRyMDdMTk1YR210ME1VWDhZaVNG
            WENyYzZVdmZuQ0FPazRha2NlS3VFSlkKLS0tIExDanRYNnhiRlczaTF5U1lBWmE5
            VUZlRUkrK2E3bnFiT2lwN1BKVHRtcG8KdL3D2Sr8SPUNdTN8zc7V56xGva5P8jwS
            5hA27YhOrp+Nme8unpODA6Ziak9UQh/ShAQaJN0dR25flybSZTM3VA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-29T20:50:34Z"
    mac: ENC[AES256_GCM,data:4BltxI20rmzm4laYOh1tc3I+cy9Hm6KMez4d7FIBvL0NyW5vr5r71hC5L+C0XJV+rraIcJUcBV12iYTD+D+0OhuTiGsWMDxILQv6oSvReqXDEUIkR+Ie4AS8FFWNgw3lfnNLq+JsXokTjZEHzJHt43/zrISmqFDX+ropuidpQmo=,iv:0kdoos76t9xeeWB3vEnLM5M7MLWhR3h1wrz7dFOr6k8=,tag:aVxN/THZ1l6P0IPU0szGJg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
