argo-cd:
    global:
        image:
            repository: registry.digitalocean.com/une-k8s/core/argocd
            tag: v2.1.2
        imagePullSecrets:
            - name: do-docker-registry
    createAggregateRoles: true
    server:
        certificate:
            domain: argo.unerror.network
            enabled: true
            issuer:
                kind: ClusterIssuer
                name: letsencrypt-prod
        rbacConfig:
            policy.default: role:readonly
            policy.csv: |
              g, unerror:unerror-team, role:admin
              g, terraform, role:admin
        config:
          url: https://argo.unerror.network
          accounts.terraform: apiKey
          repositories: |
            - type: helm
              name: stable
              url: https://charts.helm.sh/stable
            - type: helm
              name: argo-cd
              url: https://argoproj.github.io/argo-helm
        ingress:
            enabled: true
            ingressClassName: nginx
            https: true
            tls:
            - hosts:
                - argo.unerror.network
              secretName: argo-unerror-network-cert
            annotations:
                cert-manager.io/cluster-issuer: letsencrypt-prod
                nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
            hosts:
            - argo.unerror.network
    repoServer:
        env:
          - name: SOPS_AGE_KEY_FILE
            value: /sops/keys.txt
        volumeMounts:
        - name: age-keyfile
          mountPath: "/sops"
          readOnly: true
        volumes:
        - name: age-keyfile
          secret:
            secretName: age-keyfile