argo-cd:
  global:
    image:
      repository: registry.digitalocean.com/une-k8s/core/argocd
      tag: v2.1.2
    imagePullSecrets:
      - name: do-docker-registry
  createAggregateRoles: true
  controller:
    extraArgs:
      - --repo-server-timeout-seconds
      - "500"
      - --status-processors
      - "10"
      - --operation-processors
      - "5"
  server:
    certificate:
      domain: argo.unerror.network
      enabled: true
      issuer:
        kind: ClusterIssuer
        name: letsencrypt-prod
    rbacConfig:
      policy.default: role:readonly
      policy.csv: |
        g, unerror:unerror-team, role:admin
        g, terraform, role:admin
    config:
      url: https://argo.unerror.network
      accounts.terraform: apiKey
      repositories: |
        - type: helm
          name: stable
          url: https://charts.helm.sh/stable
        - type: helm
          name: argo-cd
          url: https://argoproj.github.io/argo-helm
    ingress:
      enabled: true
      ingressClassName: networking-traefik
      https: true
      tls:
        - hosts:
            - argo.unerror.network
          secretName: argo-unerror-network-cert
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
        traefik.ingress.kubernetes.io/router.tls.options: default
      hosts:
        - argo.unerror.network
  repoServer:
    replicas: 3
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/component
                  operator: In
                  values:
                    - repo-server
            topologyKey: "kubernetes.io/hostname"
    env:
      - name: ARGOCD_EXEC_TIMEOUT
        value: "5m"
      - name: SOPS_AGE_KEY_FILE
        value: /sops/keys.txt
    volumeMounts:
      - name: age-keyfile
        mountPath: "/sops"
        readOnly: true
    volumes:
      - name: age-keyfile
        secret:
          secretName: age-keyfile
